// SPDX-License-Identifier: BSD-3-Clause
//
// Generated by idlc from lib/launch/Startup.swift. Do not edit.
//
// Library todhchai.launch, version 1: the client side in C.
// Strings are pointer plus length (UTF-8, not NUL-terminated); optional
// values are pointers, NULL when absent (TD_HANDLE_INVALID for handles).
// What a reply returns points into the message buffer the call was
// given, and into the arena for vectors' elements and optional values.

#ifndef LAUNCH_IPC_IDL_H
#define LAUNCH_IPC_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <td_wire.h>

#ifdef __cplusplus
extern "C" {
#endif

#define STARTUP_PROTOCOL_ID "todhchai.launch.Startup"
#define STARTUP_VERSION 1
#define STARTUP_INFO_ORDINAL UINT64_C(0xa36ec2336de6c41)
#define STARTUP_MOUNT_ORDINAL UINT64_C(0x77a54594702a3e6e)
#define STARTUP_EXPORT_ORDINAL UINT64_C(0x59530effb78dfaf)
#define STARTUP_BOARD_ORDINAL UINT64_C(0x76561e74ef950587)
#define STARTUP_READY_ORDINAL UINT64_C(0x1373d6a6117fa340)

// StartupError: codes in error replies (td_wire_call returns TD_ERR_REMOTE).
#define STARTUP_ERROR_NOT_FOUND 1
#define STARTUP_ERROR_TAKEN 2

// enum Placement (UInt8): receivers reject other values.
typedef uint8_t launch_ipc_placement_t;
#define LAUNCH_IPC_PLACEMENT_REPLACE ((launch_ipc_placement_t)1)
#define LAUNCH_IPC_PLACEMENT_BEFORE ((launch_ipc_placement_t)2)
#define LAUNCH_IPC_PLACEMENT_AFTER ((launch_ipc_placement_t)3)
static inline int launch_ipc_placement_known(uint64_t v) { return v == UINT64_C(1) || v == UINT64_C(2) || v == UINT64_C(3); }

typedef struct launch_ipc_start_info launch_ipc_start_info_t;
typedef struct launch_ipc_mount_entry launch_ipc_mount_entry_t;

typedef struct launch_ipc_vec_str {
  const td_wire_str_t *items;
  uint32_t count;
} launch_ipc_vec_str_t;

struct launch_ipc_start_info {
  td_wire_str_t name;
  launch_ipc_vec_str_t args;
  bool sealed;
  uint32_t mounts;
};

struct launch_ipc_mount_entry {
  td_wire_str_t path;
  td_handle_t node;
  launch_ipc_placement_t placement;
  bool create;
};

static inline td_status_t launch_ipc_start_info_encode(td_wire_msg_t *m, uint32_t o, const launch_ipc_start_info_t *in);
static inline td_status_t launch_ipc_start_info_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, launch_ipc_start_info_t *out);
static inline td_status_t launch_ipc_mount_entry_encode(td_wire_msg_t *m, uint32_t o, const launch_ipc_mount_entry_t *in);
static inline td_status_t launch_ipc_mount_entry_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, launch_ipc_mount_entry_t *out);

static inline td_status_t launch_ipc_start_info_encode(td_wire_msg_t *m, uint32_t o, const launch_ipc_start_info_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = td_wire_store_bytes(m, o + 0, (in->name).data, (in->name).len)) != TD_OK) return s;
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, o + 16, (in->args).count, 16, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (in->args).count; i0++) {
  if ((s = td_wire_store_bytes(m, b0 + i0 * 16, ((in->args).items[i0]).data, ((in->args).items[i0]).len)) != TD_OK) return s;
  }
  }
  td_wire_store(m, o + 32, (in->sealed) ? 1 : 0, 1);
  td_wire_store(m, o + 36, (uint64_t)(in->mounts), 4);
  return TD_OK;
}

static inline td_status_t launch_ipc_start_info_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, launch_ipc_start_info_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 33, 3) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_string(r, o + 0, &(out->name).data, &(out->name).len) != TD_OK) return TD_ERR_PROTOCOL;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, o + 16, 16, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  td_wire_str_t *e0 = (td_wire_str_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(td_wire_str_t), (uint32_t)_Alignof(td_wire_str_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if (td_wire_load_string(r, b0 + i0 * 16, &(e0[i0]).data, &(e0[i0]).len) != TD_OK) return TD_ERR_PROTOCOL;
  }
  (out->args).items = (const td_wire_str_t *)e0;
  (out->args).count = n0;
  }
  { uint8_t b; if (td_wire_load_bool(r, o + 32, &b) != TD_OK) return TD_ERR_PROTOCOL; out->sealed = b; }
  if (td_wire_load(r, o + 36, 4, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->mounts = (uint32_t)(uint32_t)v;
  return TD_OK;
}

static inline td_status_t launch_ipc_mount_entry_encode(td_wire_msg_t *m, uint32_t o, const launch_ipc_mount_entry_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = td_wire_store_bytes(m, o + 0, (in->path).data, (in->path).len)) != TD_OK) return s;
  if ((s = td_wire_store_handle(m, o + 16, in->node)) != TD_OK) return s;
  td_wire_store(m, o + 20, (uint64_t)(in->placement), 1);
  td_wire_store(m, o + 21, (in->create) ? 1 : 0, 1);
  return TD_OK;
}

static inline td_status_t launch_ipc_mount_entry_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, launch_ipc_mount_entry_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 22, 2) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_string(r, o + 0, &(out->path).data, &(out->path).len) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_handle(r, o + 16, &(out->node)) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 20, 1, &v) != TD_OK || !launch_ipc_placement_known(v)) return TD_ERR_PROTOCOL;
  out->placement = (launch_ipc_placement_t)(uint8_t)v;
  { uint8_t b; if (td_wire_load_bool(r, o + 21, &b) != TD_OK) return TD_ERR_PROTOCOL; out->create = b; }
  return TD_OK;
}

// info: encodes the request. txid is the caller's, nonzero.
static inline td_status_t startup_info_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, STARTUP_INFO_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// info: decodes the reply.
static inline td_status_t startup_info_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, launch_ipc_start_info_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 40) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = launch_ipc_start_info_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// info: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t startup_info(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, td_wire_arena_t *arena, launch_ipc_start_info_t *result) {
  td_status_t s = startup_info_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return startup_info_decode_reply(buf, arena, result);
}

// mount: encodes the request. txid is the caller's, nonzero.
static inline td_status_t startup_mount_encode(td_wire_msg_t *m, uint32_t txid, uint32_t index) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, STARTUP_MOUNT_ORDINAL, 8);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(index), 4);
  return TD_OK;
}

// mount: decodes the reply.
static inline td_status_t startup_mount_decode_reply(const td_wire_msg_t *m, launch_ipc_mount_entry_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 24) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = launch_ipc_mount_entry_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// mount: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t startup_mount(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint32_t index, launch_ipc_mount_entry_t *result) {
  td_status_t s = startup_mount_encode(buf, txid, index);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return startup_mount_decode_reply(buf, result);
}

// export: encodes the request. txid is the caller's, nonzero.
static inline td_status_t startup_export_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, STARTUP_EXPORT_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// export: decodes the reply.
static inline td_status_t startup_export_decode_reply(const td_wire_msg_t *m, td_handle_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 8) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_check_padding(r, 4, 4) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_handle(r, 0, &((*result))) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// export: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t startup_export(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, td_handle_t *result) {
  td_status_t s = startup_export_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return startup_export_decode_reply(buf, result);
}

// board: encodes the request. txid is the caller's, nonzero.
static inline td_status_t startup_board_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, STARTUP_BOARD_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// board: decodes the reply.
static inline td_status_t startup_board_decode_reply(const td_wire_msg_t *m, td_handle_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 8) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_check_padding(r, 4, 4) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_handle(r, 0, &((*result))) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// board: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t startup_board(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, td_handle_t *result) {
  td_status_t s = startup_board_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return startup_board_decode_reply(buf, result);
}

// ready: encodes the request. txid is the caller's, nonzero.
static inline td_status_t startup_ready_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, STARTUP_READY_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// ready: decodes the reply.
static inline td_status_t startup_ready_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// ready: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t startup_ready(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code) {
  td_status_t s = startup_ready_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return startup_ready_decode_reply(buf);
}

#ifdef __cplusplus
}
#endif

#endif
