// SPDX-License-Identifier: BSD-3-Clause

// Writes the generated types as Swift source. Every encode and decode
// follows the method's Layout, field by field, so the code is the wire
// format spelled out (docs/wire-format.md).

import SwiftSyntax

struct Generator {
  let name: String
  let access: String
  let methods: [Method]

  func declarations() -> [DeclSyntax] {
    [client(), handler(), server(), events()].map { DeclSyntax(stringLiteral: $0) }
  }

  // MARK: Pieces shared by client and server

  func hex(_ value: UInt64) -> String { "0x" + String(value, radix: 16) }

  func errorType(_ m: Method) -> String { m.errorType ?? "Never" }

  /// Statements that store `layout`'s fields, which are named by `valueName`.
  func stores(_ layout: Layout, _ valueName: (Field) -> String) -> String {
    layout.fields.map { f in
      let v = valueName(f)
      switch f.type {
      case .integer: return "try e.store(\(v), at: \(f.offset))"
      case .bool: return "try e.storeBool(\(v), at: \(f.offset))"
      case .string: return "try e.storeString(\(v), at: \(f.offset))"
      case .handle: return "try e.storeHandle(\(v), at: \(f.offset))"
      }
    }.joined(separator: "\n")
  }

  /// An expression that loads `f`.
  func load(_ f: Field) -> String {
    switch f.type {
    case .integer(let swiftType, _): "try d.load(\(swiftType).self, at: \(f.offset))"
    case .bool: "try d.loadBool(at: \(f.offset))"
    case .string: "try d.loadString(at: \(f.offset))"
    case .handle: "try d.loadRequiredHandle(at: \(f.offset))"
    }
  }

  /// A closure body that loads every field of `layout`, checks its padding
  /// and returns the values (a tuple, one value, or nothing).
  func loads(_ layout: Layout) -> String {
    let checks = layout.padding.map { "try d.checkPadding(at: \($0.offset), count: \($0.count))" }
    // Loads run in field order, which out-of-line data requires.
    let bindings = layout.fields.indices.map { "let v\($0) = \(load(layout.fields[$0]))" }
    let tuple = layout.fields.indices.map { "v\($0)" }
    return (checks + bindings + [
      tuple.isEmpty ? "return ()" : tuple.count == 1 ? "return v0" : "return (\(tuple.joined(separator: ", ")))"
    ]).joined(separator: "\n")
  }

  /// The parameter list as declared, for the handler protocol and client.
  func parameterList(_ m: Method, handlesConsumed: Bool = true) -> String {
    m.parameters.map { p in
      let label = p.label.map { $0 == p.name ? $0 : "\($0) \(p.name)" } ?? "_ \(p.name)"
      let type = p.type == .handle && handlesConsumed ? "consuming Handle" : p.swiftType
      return "\(label): \(type)"
    }.joined(separator: ", ")
  }

  func throwsClause(_ m: Method) -> String {
    m.errorType.map { " throws(\($0))" } ?? ""
  }

  func resultClause(_ m: Method) -> String {
    m.result.map { " -> \($0.swiftType)" } ?? ""
  }

  /// "ticked" → "Ticked"
  func capitalized(_ s: String) -> String { s.prefix(1).uppercased() + s.dropFirst() }

  // MARK: Client

  func client() -> String {
    let calls = methods.filter { $0.kind != .event }.map(clientMethod).joined(separator: "\n\n")
    let hasEvents = methods.contains { $0.kind == .event }
    let nextEvent = hasEvents ? """

      /// The next event: one that arrived during a call, or the next to
      /// arrive before `deadline` (monotonic nanoseconds).
      public mutating func nextEvent(deadline: Int64 = infiniteDeadline) throws(IPCError<Never>) -> \(name)Event {
        let (header, message) = try connection.nextEvent(deadline: deadline)
        return try \(name)Event.decode(header, message)
      }
      """ : ""
    return """
      /// Calls `\(name)` over a channel. Generated by @IPCProtocol.
      \(access)struct \(name)Client: ~Copyable {
        public var connection: IPCClientConnection

        public init(channel: consuming Handle) {
          connection = IPCClientConnection(channel: channel)
        }

      \(calls)
      \(nextEvent)
      }
      """
  }

  func clientMethod(_ m: Method) -> String {
    let e = errorType(m)
    let req = m.request
    let handles = m.parameters.filter { $0.type == .handle }
    // Handles are released first: the message owns them from here on.
    let releases = handles.map { "let h_\($0.name) = \($0.name).release()" }.joined(separator: "\n")
    let closing = "[" + handles.map { "h_\($0.name)" }.joined(separator: ", ") + "]"
    let body = stores(req) { f in
      let p = String(f.name.dropFirst(2))
      return f.type == .handle ? "h_\(p)" : p
    }
    let txid = m.kind == .call ? "connection.takeTxid()" : "UInt32(0)"
    var lines = [
      releases,
      "let txid = \(txid)",
      """
      let request = try IPCCodec.encode(
        MessageHeader(txid: txid, kind: .request, ordinal: \(hex(m.ordinal))),
        inlineSize: \(req.size), closing: \(closing), \(e).self
      ) { (e: inout Encoder) throws(WireError) in
      \(body)
      }
      """,
    ]
    if m.kind == .oneway {
      lines.append("try connection.send(request, \(e).self)")
    } else {
      let reply = m.reply
      lines.append("let reply = try connection.call(request, txid: txid, \(e).self)")
      lines.append("""
        let result = try IPCCodec.decode(reply, inlineSize: \(reply.size), \(e).self) { (d: inout Decoder) throws(WireError) in
        \(loads(reply))
        }
        """)
      if let r = m.result {
        lines.append(r.type == .handle ? "return Handle(raw: result)" : "return result")
      } else {
        lines.append("_ = result")
      }
    }
    return """
      public mutating func \(m.name)(\(parameterList(m))) throws(IPCError<\(e)>)\(resultClause(m)) {
      \(lines.filter { !$0.isEmpty }.joined(separator: "\n"))
      }
      """
  }

  // MARK: Handler

  func handler() -> String {
    let requirements = methods.filter { $0.kind != .event }.map { m in
      "mutating func \(m.name)(\(parameterList(m)))\(throwsClause(m))\(resultClause(m))"
    }.joined(separator: "\n")
    return """
      /// What a `\(name)` server implements. Generated by @IPCProtocol.
      \(access)protocol \(name)Handler {
      \(requirements)
      }
      """
  }

  // MARK: Server

  func server() -> String {
    let cases = methods.filter { $0.kind != .event }.map(serverCase).joined(separator: "\n")
    let senders = methods.filter { $0.kind == .event }.map(eventSender).joined(separator: "\n\n")
    return """
      /// Serves `\(name)` on a channel, calling a handler. Generated by @IPCProtocol.
      \(access)struct \(name)Server<Impl: \(name)Handler>: ~Copyable {
        public var connection: IPCServerConnection
        public var impl: Impl

        public init(channel: consuming Handle, impl: Impl) {
          connection = IPCServerConnection(channel: channel)
          self.impl = impl
        }

        /// Serves requests until the client closes its end.
        public mutating func serve() throws(IPCError<Never>) {
          while try handleNext() {}
        }

        /// Serves one request; false once the client has closed its end.
        public mutating func handleNext() throws(IPCError<Never>) -> Bool {
          guard let (header, message) = try connection.nextRequest() else { return false }
          switch header.ordinal {
      \(cases)
          default:
            try connection.unknownMethod(header, message)
          }
          return true
        }

      \(senders)
      }
      """
  }

  func serverCase(_ m: Method) -> String {
    let req = m.request
    let count = req.fields.count
    let names = (0..<count).map { "a\($0)" }
    let bind = count == 0 ? "_" : count == 1 ? "let a0" : "let (" + names.joined(separator: ", ") + ")"
    let arguments = m.parameters.enumerated().map { i, p in
      let value = p.type == .handle ? "Handle(raw: a\(i))" : "a\(i)"
      return p.label.map { "\($0): \(value)" } ?? value
    }.joined(separator: ", ")
    let invoke = "\(m.errorType == nil ? "" : "try ")impl.\(m.name)(\(arguments))"

    var body = """
          try connection.expect(header, twoWay: \(m.kind == .call), message)
          \(bind) = try IPCCodec.decode(message, inlineSize: \(req.size), Never.self) { (d: inout Decoder) throws(WireError) in
      \(loads(req))
          }
      """
    if m.kind == .oneway {
      body += "\n\(invoke)"
    } else {
      let reply = m.reply
      let resultRelease = m.result?.type == .handle ? "\nlet h_r = r.release()" : ""
      let closing = m.result?.type == .handle ? "[h_r]" : "[]"
      let store = stores(reply) { _ in m.result?.type == .handle ? "h_r" : "r" }
      let send = """
        let replyMessage = try IPCCodec.encode(
          MessageHeader(txid: header.txid, kind: .reply, ordinal: header.ordinal),
          inlineSize: \(reply.size), closing: \(closing), Never.self
        ) { (e: inout Encoder) throws(WireError) in
        \(store)
        }
        try connection.send(replyMessage)
        """
      if let errorType = m.errorType {
        // The handler's error is caught alone: an error reply, then on to
        // the next request.
        let declare = m.result.map { "let r: \($0.swiftType)" } ?? ""
        let assign = m.result == nil ? invoke : "r = \(invoke)"
        body += """

          \(declare)
          do throws(\(errorType)) {
            \(assign)
          } catch {
            try connection.replyError(to: header, code: error.code)
            return true
          }\(resultRelease)
          \(send)
          """
      } else {
        let produce = m.result == nil ? invoke : "let r = \(invoke)\(resultRelease)"
        body += "\n\(produce)\n\(send)"
      }
    }
    return """
          case \(hex(m.ordinal)):  // \(m.name)
      \(body)
      """
  }

  func eventSender(_ m: Method) -> String {
    let body = stores(m.request) { f in String(f.name.dropFirst(2)) }
    return """
      /// Sends the `\(m.name)` event.
      public func send\(capitalized(m.name))(\(parameterList(m))) throws(IPCError<Never>) {
        let event = try IPCCodec.encode(
          MessageHeader(txid: 0, kind: .event, ordinal: \(hex(m.ordinal))),
          inlineSize: \(m.request.size), Never.self
        ) { (e: inout Encoder) throws(WireError) in
      \(body)
        }
        try connection.send(event)
      }
      """
  }

  // MARK: Events

  func events() -> String {
    let events = methods.filter { $0.kind == .event }
    let cases = events.map { m in
      let associated = m.parameters.map { p in
        p.label.map { "\($0): \(p.swiftType)" } ?? p.swiftType
      }.joined(separator: ", ")
      return "case \(m.name)" + (associated.isEmpty ? "" : "(\(associated))")
    }.joined(separator: "\n")
    let decodeCases = events.map { m in
      let count = m.parameters.count
      let bind = count == 0 ? "_" : count == 1 ? "let a0" : "let (" + (0..<count).map { "a\($0)" }.joined(separator: ", ") + ")"
      let args = m.parameters.enumerated().map { i, p in p.label.map { "\($0): a\(i)" } ?? "a\(i)" }
        .joined(separator: ", ")
      return """
          case \(hex(m.ordinal)):
            \(bind) = try IPCCodec.decode(message, inlineSize: \(m.request.size), Never.self) { (d: inout Decoder) throws(WireError) in
        \(loads(m.request))
            }
            return .\(m.name)\(count == 0 ? "" : "(\(args))")
        """
    }.joined(separator: "\n")
    return """
      /// The events of `\(name)`. Generated by @IPCProtocol.
      \(access)enum \(name)Event {
      \(cases)

        static func decode(_ header: MessageHeader, _ message: IPCMessage) throws(IPCError<Never>) -> \(name)Event {
          switch header.ordinal {
      \(decodeCases)
          default:
            message.closeHandles()
            throw .wire(.unexpectedMessage)
          }
        }
      }
      """
  }
}
