// SPDX-License-Identifier: BSD-3-Clause

// fontgen's work: reads a fixed-cell BDF font (Adobe's Glyph Bitmap
// Distribution Format 2.1) and writes it as a Swift table for
// lib/console's `Font`: the code points in order, and each glyph's rows
// placed in the cell by the font's baseline, a row being `(width + 7) / 8`
// bytes, the leftmost pixel the high bit. The output is the font's data
// in another form, so it keeps the font's license: the header names it.

public struct BDFFont: Equatable, Sendable {
  public var width: Int
  public var height: Int
  public var glyphs: [(codepoint: UInt32, rows: [UInt8])]

  public static func == (a: Self, b: Self) -> Bool {
    a.width == b.width && a.height == b.height && a.glyphs.count == b.glyphs.count
      && zip(a.glyphs, b.glyphs).allSatisfy { $0.codepoint == $1.codepoint && $0.rows == $1.rows }
  }

  public enum Failure: Error, Equatable {
    case malformed(line: Int, String)
  }

  public var bytesPerRow: Int { (width + 7) / 8 }

  /// Glyphs with no encoding (ENCODING -1) are left out.
  public init(bdf text: String) throws(Failure) {
    var width = 0, height = 0, descent = 0
    var glyphs: [(UInt32, [UInt8])] = []
    var encoding: Int?
    var box = (w: 0, h: 0, x: 0, y: 0)
    var bitmap: [String]?
    for (n, raw) in text.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
      let words = raw.split(separator: " ").map(String.init)
      guard let key = words.first else { continue }
      let numbers = words.dropFirst().compactMap { Int($0) }
      if var rows = bitmap {
        if key == "ENDCHAR" {
          guard let e = encoding else { throw .malformed(line: n + 1, "no ENCODING") }
          bitmap = nil
          if e < 0 { continue }
          let bpr = (width + 7) / 8
          var cell = [UInt8](repeating: 0, count: height * bpr)
          // The glyph's top row in the cell: the ascent less its top.
          let top = (height - descent) - (box.y + box.h)
          for (r, hex) in rows.enumerated() {
            guard var bits = UInt64(hex, radix: 16) else { throw .malformed(line: n + 1, "bad bitmap row") }
            let rowBits = hex.count * 4
            // Pixel i of the glyph is bit (rowBits - 1 - i); it goes to column box.x + i.
            for i in 0..<box.w where bits >> UInt64(rowBits - 1 - i) & 1 == 1 {
              let col = box.x + i, row = top + r
              guard col >= 0, col < width, row >= 0, row < height else {
                throw .malformed(line: n + 1, "glyph \(e) leaves its cell")
              }
              cell[row * bpr + col / 8] |= 0x80 >> UInt8(col % 8)
            }
            bits = 0
          }
          glyphs.append((UInt32(e), cell))
        } else {
          rows.append(key)
          bitmap = rows
        }
        continue
      }
      switch key {
      case "FONTBOUNDINGBOX":
        guard numbers.count == 4 else { throw .malformed(line: n + 1, "FONTBOUNDINGBOX") }
        (width, height, descent) = (numbers[0], numbers[1], -numbers[3])
      case "STARTCHAR":
        encoding = nil
        box = (width, height, 0, -descent)
      case "ENCODING":
        encoding = numbers.first
      case "BBX":
        guard numbers.count == 4 else { throw .malformed(line: n + 1, "BBX") }
        box = (numbers[0], numbers[1], numbers[2], numbers[3])
      case "BITMAP":
        bitmap = []
      default:
        break
      }
    }
    guard width > 0, height > 0 else { throw .malformed(line: 0, "no FONTBOUNDINGBOX") }
    self.width = width
    self.height = height
    self.glyphs = glyphs.sorted { $0.0 < $1.0 }.map { (codepoint: $0.0, rows: $0.1) }
  }
}

/// The Swift source of `fonts` (name, font) as static `Font`s, under a
/// header naming the fonts' license (`spdx`) and `notice`.
public func swiftTable(_ fonts: [(name: String, font: BDFFont)], spdx: String, notice: [String]) -> String {
  var out = "// SPDX-License-Identifier: \(spdx)\n"
  for line in notice { out += "// \(line)\n" }
  out += "//\n// Generated by fontgen; don't edit.\n\nextension Font {\n"
  for (name, font) in fonts {
    out += "  public static let \(name) = Font(\n"
    out += "    width: \(font.width), height: \(font.height),\n"
    out += "    codepoints: [\n"
    var line = "     "
    for g in font.glyphs {
      let item = " 0x\(String(g.codepoint, radix: 16, uppercase: true)),"
      if line.count + item.count > 116 {
        out += line + "\n"
        line = "     "
      }
      line += item
    }
    out += line + "\n    ],\n    bitmaps: [\n"
    for g in font.glyphs {
      out += "      " + g.rows.map { "0x" + (($0 < 16 ? "0" : "") + String($0, radix: 16, uppercase: true)) }
        .joined(separator: ", ") + ",\n"
    }
    out += "    ])\n"
  }
  out += "}\n"
  return out
}

/// The header of the Spleen table: its license, copyright and source.
public let spleenNotice = [
  "Spleen 2.1.0, Copyright (c) 2018-2024, Frederic Cambus. All rights reserved.",
  "Third-party data (principle 29) under its own BSD 2-Clause license, in",
  "data/fonts/spleen/LICENSE, whose conditions travel with it; its provenance",
  "is data/fonts/spleen/PROVENANCE.md. Converted from its BDF files: each",
  "glyph's rows in an 8x16 or 16x32 cell, leftmost pixel the high bit.",
]
