// SPDX-License-Identifier: BSD-3-Clause

// The host's Vulkan loader (libvulkan.so.1), opened at run time: it is the
// platform's interface to the GPU driver (architecture §18). Commands come
// through vkGetInstanceProcAddr and vkGetDeviceProcAddr into
// VulkanCommands (generated by vkgen).

import Glibc
@_exported import TDVulkan

public enum VulkanError: Error, Equatable {
  /// No Vulkan loader on this host (libvulkan.so.1).
  case noLoader
  /// A call returned an error.
  case failed(String, VkResult)
  /// A command the driver doesn't provide.
  case missing(String)
}

/// The loader library and the commands loaded from it.
public final class VulkanLibrary: @unchecked Sendable {
  let handle: UnsafeMutableRawPointer
  public let getInstanceProcAddr: PFN_vkGetInstanceProcAddr
  public var commands = VulkanCommands()

  public init() throws(VulkanError) {
    guard let handle = dlopen("libvulkan.so.1", RTLD_NOW | RTLD_LOCAL) else { throw .noLoader }
    guard let symbol = dlsym(handle, "vkGetInstanceProcAddr") else {
      dlclose(handle)
      throw .noLoader
    }
    self.handle = handle
    getInstanceProcAddr = unsafeBitCast(symbol, to: PFN_vkGetInstanceProcAddr.self)
    commands.loadGlobal(getInstanceProcAddr)
  }

  deinit { dlclose(handle) }

  public func loadInstance(_ instance: VkInstance) { commands.loadInstance(getInstanceProcAddr, instance) }

  public func loadDevice(_ device: VkDevice) throws(VulkanError) {
    guard let get = commands.vkGetDeviceProcAddr else { throw .missing("vkGetDeviceProcAddr") }
    commands.loadDevice(get, device)
  }
}

/// Throws unless `result` is VK_SUCCESS.
public func check(_ result: VkResult, _ what: String) throws(VulkanError) {
  guard result == VK_SUCCESS else { throw .failed(what, result) }
}

/// The version number Vulkan uses: variant 0, then major, minor, patch.
public func vulkanVersion(_ major: UInt32, _ minor: UInt32, _ patch: UInt32 = 0) -> UInt32 {
  major << 22 | minor << 12 | patch
}
