// SPDX-License-Identifier: BSD-3-Clause
//
// Generated by idlc from lib/block/Block.swift. Do not edit.
//
// Library todhchai.block, version 1: the client side in C.
// Strings are pointer plus length (UTF-8, not NUL-terminated); optional
// values are pointers, NULL when absent (TD_HANDLE_INVALID for handles).
// What a reply returns points into the message buffer the call was
// given, and into the arena for vectors' elements and optional values.

#ifndef BLOCK_IPC_IDL_H
#define BLOCK_IPC_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <td_wire.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DEVICE_PROTOCOL_ID "todhchai.block.Device"
#define DEVICE_VERSION 1
#define DEVICE_INFO_ORDINAL UINT64_C(0x18ead7e23949e918)
#define DEVICE_OPEN_ORDINAL UINT64_C(0x102308cff86770e4)
#define DEVICE_ATTACH_ORDINAL UINT64_C(0x1f84b8f77eef0b09)
#define DEVICE_DETACH_ORDINAL UINT64_C(0x6630ccceb40c6c33)

// BlockError: codes in error replies (td_wire_call returns TD_ERR_REMOTE).
#define BLOCK_ERROR_INVALID 1
#define BLOCK_ERROR_ALREADY_OPEN 2
#define BLOCK_ERROR_NOT_FOUND 3
#define BLOCK_ERROR_TOO_MANY 4
#define BLOCK_ERROR_NO_RESOURCES 5

typedef struct block_ipc_device_info block_ipc_device_info_t;
typedef struct block_ipc_ring block_ipc_ring_t;

struct block_ipc_device_info {
  uint32_t block_size;
  uint64_t block_count;
  uint32_t max_transfer;
  bool read_only;
};

struct block_ipc_ring {
  td_handle_t vmo;
  td_handle_t signal;
};

static inline td_status_t block_ipc_device_info_encode(td_wire_msg_t *m, uint32_t o, const block_ipc_device_info_t *in);
static inline td_status_t block_ipc_device_info_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, block_ipc_device_info_t *out);
static inline td_status_t block_ipc_ring_encode(td_wire_msg_t *m, uint32_t o, const block_ipc_ring_t *in);
static inline td_status_t block_ipc_ring_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, block_ipc_ring_t *out);

static inline td_status_t block_ipc_device_info_encode(td_wire_msg_t *m, uint32_t o, const block_ipc_device_info_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  td_wire_store(m, o + 0, (uint64_t)(in->block_size), 4);
  td_wire_store(m, o + 8, (uint64_t)(in->block_count), 8);
  td_wire_store(m, o + 16, (uint64_t)(in->max_transfer), 4);
  td_wire_store(m, o + 20, (in->read_only) ? 1 : 0, 1);
  return TD_OK;
}

static inline td_status_t block_ipc_device_info_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, block_ipc_device_info_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 4, 4) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_check_padding(r, o + 21, 3) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 0, 4, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->block_size = (uint32_t)(uint32_t)v;
  if (td_wire_load(r, o + 8, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->block_count = (uint64_t)(uint64_t)v;
  if (td_wire_load(r, o + 16, 4, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->max_transfer = (uint32_t)(uint32_t)v;
  { uint8_t b; if (td_wire_load_bool(r, o + 20, &b) != TD_OK) return TD_ERR_PROTOCOL; out->read_only = b; }
  return TD_OK;
}

static inline td_status_t block_ipc_ring_encode(td_wire_msg_t *m, uint32_t o, const block_ipc_ring_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = td_wire_store_handle(m, o + 0, in->vmo)) != TD_OK) return s;
  if ((s = td_wire_store_handle(m, o + 4, in->signal)) != TD_OK) return s;
  return TD_OK;
}

static inline td_status_t block_ipc_ring_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, block_ipc_ring_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_load_handle(r, o + 0, &(out->vmo)) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_handle(r, o + 4, &(out->signal)) != TD_OK) return TD_ERR_PROTOCOL;
  return TD_OK;
}

// info: encodes the request. txid is the caller's, nonzero.
static inline td_status_t device_info_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DEVICE_INFO_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// info: decodes the reply.
static inline td_status_t device_info_decode_reply(const td_wire_msg_t *m, block_ipc_device_info_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 24) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = block_ipc_device_info_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// info: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t device_info(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, block_ipc_device_info_t *result) {
  td_status_t s = device_info_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return device_info_decode_reply(buf, result);
}

// open: encodes the request. txid is the caller's, nonzero.
static inline td_status_t device_open_encode(td_wire_msg_t *m, uint32_t txid, uint32_t entries) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DEVICE_OPEN_ORDINAL, 8);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(entries), 4);
  return TD_OK;
}

// open: decodes the reply.
static inline td_status_t device_open_decode_reply(const td_wire_msg_t *m, block_ipc_ring_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 8) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = block_ipc_ring_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// open: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t device_open(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint32_t entries, block_ipc_ring_t *result) {
  td_status_t s = device_open_encode(buf, txid, entries);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return device_open_decode_reply(buf, result);
}

// attach: encodes the request. txid is the caller's, nonzero.
static inline td_status_t device_attach_encode(td_wire_msg_t *m, uint32_t txid, td_handle_t vmo) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DEVICE_ATTACH_ORDINAL, 8);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_handle(m, 0, vmo)) != TD_OK) return s;
  return TD_OK;
}

// attach: decodes the reply.
static inline td_status_t device_attach_decode_reply(const td_wire_msg_t *m, uint32_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 8) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_check_padding(r, 4, 4) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, 0, 4, &v) != TD_OK) return TD_ERR_PROTOCOL;
  (*result) = (uint32_t)(uint32_t)v;
  return td_wire_read_end(r);
}

// attach: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t device_attach(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, td_handle_t vmo, uint32_t *result) {
  td_status_t s = device_attach_encode(buf, txid, vmo);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return device_attach_decode_reply(buf, result);
}

// detach: encodes the request. txid is the caller's, nonzero.
static inline td_status_t device_detach_encode(td_wire_msg_t *m, uint32_t txid, uint32_t buffer) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DEVICE_DETACH_ORDINAL, 8);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(buffer), 4);
  return TD_OK;
}

// detach: decodes the reply.
static inline td_status_t device_detach_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// detach: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t device_detach(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint32_t buffer) {
  td_status_t s = device_detach_encode(buf, txid, buffer);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return device_detach_decode_reply(buf);
}

#ifdef __cplusplus
}
#endif

#endif
