// SPDX-License-Identifier: BSD-3-Clause

// The C header idlc writes for a protocol: its constants and error codes,
// request encoders, reply and event decoders, and call wrappers, all over
// td_wire.h. It covers the client side; C servers come later.

import IPCModel

public func cHeader(_ p: ProtocolModel, errors: [String: ErrorEnum], source: String) -> String {
  let prefix = snakeCase(p.name)
  let upper = prefix.uppercased()
  let guardName = "\(upper)_IDL_H"
  var out: [String] = []
  func emit(_ s: String) { out.append(s) }

  emit("""
    // SPDX-License-Identifier: BSD-3-Clause
    //
    // Generated by idlc from \(source). Do not edit.
    //
    // Protocol \(p.id), version \(p.version): the client side in C.
    // Strings are pointer plus length (UTF-8, not NUL-terminated). Strings a
    // reply returns point into the message buffer the call was given.

    #ifndef \(guardName)
    #define \(guardName)

    #include <stdbool.h>
    #include <stdint.h>
    #include <td_wire.h>

    #ifdef __cplusplus
    extern "C" {
    #endif

    #define \(upper)_PROTOCOL_ID "\(p.id)"
    #define \(upper)_VERSION \(p.version)
    """)

  for m in p.methods {
    emit("#define \(upper)_\(snakeCase(m.name).uppercased())_ORDINAL UINT64_C(\(hex(m.ordinal)))")
  }

  let thrown = Set(p.methods.compactMap(\.errorType)).sorted()
  for name in thrown {
    guard let e = errors[name] else { continue }
    emit("\n// \(name): codes in error replies (td_wire_call returns TD_ERR_REMOTE).")
    for c in e.cases {
      emit("#define \(snakeCase(name).uppercased())_\(snakeCase(c.name).uppercased()) \(c.code)")
    }
  }

  for m in p.methods {
    let name = "\(prefix)_\(snakeCase(m.name))"
    let ordinalName = "\(upper)_\(snakeCase(m.name).uppercased())_ORDINAL"
    let request = m.request
    switch m.kind {
    case .call, .oneway:
      emit(encoder(name: name, ordinal: ordinalName, m: m, layout: request))
      if m.kind == .call {
        emit(decoder(name: "\(name)_decode_reply", m: m, layout: m.reply, outputs: replyOutputs(m)))
        emit(callWrapper(name: name, m: m))
      } else {
        emit(onewayWrapper(name: name, m: m))
      }
    case .event:
      emit(decoder(name: "\(name)_decode", m: m, layout: request, outputs: parameterOutputs(m)))
    }
  }

  emit("""

    #ifdef __cplusplus
    }
    #endif

    #endif
    """)
  return out.joined(separator: "\n") + "\n"
}

// MARK: Pieces

/// C parameters for a method's inputs.
func cInputs(_ m: Method) -> [String] {
  m.parameters.flatMap { p -> [String] in
    switch p.type {
    case .integer(let swiftType, _): ["\(cType(swiftType)) \(p.name)"]
    case .bool: ["bool \(p.name)"]
    case .string: ["const char *\(p.name)", "uint32_t \(p.name)_len"]
    case .handle: ["td_handle_t \(p.name)"]
    }
  }
}

/// A decoder's output: the field, the C parameters receiving it.
struct Output {
  var field: Field
  var name: String
}

func replyOutputs(_ m: Method) -> [Output] {
  m.reply.fields.map { Output(field: $0, name: "result") }
}

func parameterOutputs(_ m: Method) -> [Output] {
  zip(m.request.fields, m.parameters).map { Output(field: $0, name: $1.name) }
}

func cOutputs(_ outputs: [Output]) -> [String] {
  outputs.flatMap { o -> [String] in
    switch o.field.type {
    case .integer(let swiftType, _): ["\(cType(swiftType)) *\(o.name)"]
    case .bool: ["bool *\(o.name)"]
    case .string: ["const char **\(o.name)", "uint32_t *\(o.name)_len"]
    case .handle: ["td_handle_t *\(o.name)"]
    }
  }
}

func cType(_ swiftType: String) -> String {
  switch swiftType {
  case "UInt8": "uint8_t"
  case "Int8": "int8_t"
  case "UInt16": "uint16_t"
  case "Int16": "int16_t"
  case "UInt32": "uint32_t"
  case "Int32": "int32_t"
  case "UInt64": "uint64_t"
  default: "int64_t"
  }
}

func encoder(name: String, ordinal: String, m: Method, layout: Layout) -> String {
  let parameters = (["td_wire_msg_t *m", "uint32_t txid"] + cInputs(m)).joined(separator: ", ")
  var body = ["td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, \(ordinal), \(layout.size));",
              "if (s != TD_OK) return s;"]
  // Stores go in field order: out-of-line data follows it.
  for (field, p) in zip(layout.fields, m.parameters) {
    switch field.type {
    case .integer(_, let size):
      body.append("td_wire_store(m, \(field.offset), (uint64_t)\(p.name), \(size));")
    case .bool:
      body.append("td_wire_store(m, \(field.offset), \(p.name) ? 1 : 0, 1);")
    case .string:
      body.append("if ((s = td_wire_store_bytes(m, \(field.offset), \(p.name), \(p.name)_len)) != TD_OK) return s;")
    case .handle:
      body.append("if ((s = td_wire_store_handle(m, \(field.offset), \(p.name))) != TD_OK) return s;")
    }
  }
  body.append("return TD_OK;")
  let doc = m.kind == .call
    ? "// \(m.name): encodes the request. txid is the caller's, nonzero."
    : "// \(m.name) (one-way): encodes the request. txid must be 0."
  return """

    \(doc)
    static inline td_status_t \(name)_encode(\(parameters)) {
      \(body.joined(separator: "\n  "))
    }
    """
}

func decoder(name: String, m: Method, layout: Layout, outputs: [Output]) -> String {
  let parameters = (["const td_wire_msg_t *m"] + cOutputs(outputs)).joined(separator: ", ")
  var body = ["td_wire_reader_t r;", "uint64_t v;", "(void)v;",
              "if (td_wire_read_begin(&r, m, \(layout.size)) != TD_OK) return TD_ERR_PROTOCOL;"]
  for pad in layout.padding {
    body.append("if (td_wire_check_padding(&r, \(pad.offset), \(pad.count)) != TD_OK) return TD_ERR_PROTOCOL;")
  }
  for o in outputs {
    let f = o.field
    switch f.type {
    case .integer(let swiftType, let size):
      body.append("if (td_wire_load(&r, \(f.offset), \(size), &v) != TD_OK) return TD_ERR_PROTOCOL;")
      // Through the unsigned type of the same width, so a signed value's
      // conversion is defined.
      body.append("*\(o.name) = (\(cType(swiftType)))(uint\(size * 8)_t)v;")
    case .bool:
      body.append("{ uint8_t b; if (td_wire_load_bool(&r, \(f.offset), &b) != TD_OK) return TD_ERR_PROTOCOL; *\(o.name) = b; }")
    case .string:
      body.append("if (td_wire_load_string(&r, \(f.offset), \(o.name), \(o.name)_len) != TD_OK) return TD_ERR_PROTOCOL;")
    case .handle:
      body.append("if (td_wire_load_handle(&r, \(f.offset), \(o.name)) != TD_OK) return TD_ERR_PROTOCOL;")
    }
  }
  body.append("return td_wire_read_end(&r);")
  return """

    static inline td_status_t \(name)(\(parameters)) {
      \(body.joined(separator: "\n  "))
    }
    """
}

func callWrapper(name: String, m: Method) -> String {
  let inputs = m.parameters.flatMap { p -> [String] in p.type == .string ? [p.name, "\(p.name)_len"] : [p.name] }
  let outputs = replyOutputs(m).flatMap { o -> [String] in o.field.type == .string ? [o.name, "\(o.name)_len"] : [o.name] }
  let parameters = (["td_handle_t channel", "uint32_t txid", "td_wire_msg_t *buf", "int32_t *error_code"]
    + cInputs(m) + cOutputs(replyOutputs(m))).joined(separator: ", ")
  let encodeArgs = (["buf", "txid"] + inputs).joined(separator: ", ")
  let decodeArgs = (["buf"] + outputs).joined(separator: ", ")
  return """

    // \(m.name): calls the method and waits for its reply. buf holds the
    // request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
    // the method failed.
    static inline td_status_t \(name)(\(parameters)) {
      td_status_t s = \(name)_encode(\(encodeArgs));
      if (s != TD_OK) return s;
      if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
      return \(name)_decode_reply(\(decodeArgs));
    }
    """
}

func onewayWrapper(name: String, m: Method) -> String {
  let inputs = m.parameters.flatMap { p -> [String] in p.type == .string ? [p.name, "\(p.name)_len"] : [p.name] }
  let parameters = (["td_handle_t channel", "td_wire_msg_t *buf"] + cInputs(m)).joined(separator: ", ")
  let encodeArgs = (["buf", "0"] + inputs).joined(separator: ", ")
  return """

    // \(m.name): sends the one-way request.
    static inline td_status_t \(name)(\(parameters)) {
      td_status_t s = \(name)_encode(\(encodeArgs));
      if (s != TD_OK) return s;
      return td_channel_write(channel, buf->bytes, buf->byte_count, buf->handles, buf->handle_count);
    }
    """
}
