// SPDX-License-Identifier: BSD-3-Clause

// A protocol's reference page: its methods, their ordinals, the layout of
// each message, and the structs and enums they use, from the same model
// the code comes from.

import IPCModel

public func markdown(_ p: ProtocolModel, _ library: LibraryModel, source: String,
                     composed: [Interface.ComposedMethod] = []) -> String {
  let types = library.types
  var out = """
    # \(p.name)

    Protocol `\(p.id)`, version \(p.version), of library `\(library.name)`. Generated by idlc
    from `\(source)`; the encoding rules are in `docs/wire-format.md`.

    | Method | Kind | Since | Ordinal | Parameters | Result | Error |
    |---|---|---|---|---|---|---|

    """
  for m in p.methods {
    let kind = switch m.kind {
    case .call: "call"
    case .oneway: "one-way"
    case .event: "event"
    }
    let parameters = m.parameters.map { "`\($0.name): \($0.type.swiftName)`" }.joined(separator: ", ")
    out += "| `\(m.name)` | \(kind) | \(m.since) | `\(hex(m.ordinal))` | \(parameters.isEmpty ? "—" : parameters) "
      + "| \(m.result.map { "`\($0.type.swiftName)`" } ?? "—") | \(m.errorType.map { "`\($0)`" } ?? "—") |\n"
  }
  if !composed.isEmpty {
    let ids = composed.map(\.origin.id).reduce(into: [String]()) { if !$0.contains($1) { $0.append($1) } }
    out += """

      It composes \(ids.map { "`\($0)`" }.joined(separator: ", ")): their methods are its methods, with
      their own ordinals, and are described with their protocols.

      | Method | From | Kind | Ordinal |
      |---|---|---|---|

      """
    for c in composed {
      let kind = switch c.method.kind {
      case .call: "call"
      case .oneway: "one-way"
      case .event: "event"
      }
      out += "| `\(c.method.name)` | `\(c.origin.id)` | \(kind) | `\(hex(c.method.ordinal))` |\n"
    }
  }
  for m in p.methods {
    out += "\n## \(m.name)\n\n"
    out += layoutTable(m.kind == .event ? "Event body" : "Request body", m.request, types)
    if m.kind == .call { out += "\n" + layoutTable("Reply body", m.reply, types) }
  }
  let used = p.used(types)
  for s in used.structs {
    out += "\n## struct \(s.name)\n\n"
      + layoutTable("\(s.isCopyable ? "" : "Moves (carries handles); ")aligned to \(s.alignment)", s.layout, types)
  }
  for e in used.enums {
    out += "\n## enum \(e.name)\n\n\(e.rawType); receivers reject other values.\n\n| Case | Value |\n|---|---|\n"
    for c in e.cases { out += "| `\(c.name)` | \(c.value) |\n" }
  }
  let thrown = p.methods.compactMap(\.errorType).reduce(into: [String]()) { if !$0.contains($1) { $0.append($1) } }
  for name in thrown {
    guard let e = library.errors.first(where: { $0.name == name }) else { continue }
    out += "\n## Errors: \(name)\n\n| Case | Code |\n|---|---|\n"
    for c in e.cases { out += "| `\(c.name)` | \(c.code) |\n" }
  }
  return out
}

/// How a value of `t` is stored, for the layout tables.
func storage(_ t: WireType, _ types: Types) -> String {
  switch t {
  case .integer, .bool: return ""
  case .string, .bytes: return " (count, presence; bytes out of line)"
  case .vector(let e): return " (count, presence; \(types.size(e))-byte elements out of line)"
  case .handle: return " (presence; handle in the side array)"
  case .enumeration(let n): return " (\(types.enumeration(n)?.rawType ?? "?"))"
  case .structure: return " (inline)"
  case .optional(let w): return w.hasOwnPresence ? storage(w, types) + ", absent: zero" : " (presence; boxed out of line)"
  }
}

func layoutTable(_ title: String, _ layout: Layout, _ types: Types) -> String {
  guard !layout.fields.isEmpty else { return "\(title): empty.\n" }
  var out = "\(title), \(layout.size) bytes inline:\n\n| Offset | Size | Field | Type |\n|---|---|---|---|\n"
  for f in layout.fields {
    let name = f.name == "r" ? "result" : f.name.hasPrefix("a_") ? String(f.name.dropFirst(2)) : f.name
    out += "| \(f.offset) | \(f.size) | `\(name)` | \(f.type.swiftName)\(storage(f.type, types)) |\n"
  }
  return out
}
