// SPDX-License-Identifier: BSD-3-Clause

// A protocol's reference page: its methods, their ordinals, and the inline
// layout of each message, from the same model the code comes from.

import IPCModel

public func markdown(_ p: ProtocolModel, errors: [String: ErrorEnum], source: String) -> String {
  var out = """
    # \(p.name)

    Protocol `\(p.id)`, version \(p.version). Generated by idlc from `\(source)`;
    the encoding rules are in [the wire format](wire-format.md).

    | Method | Kind | Since | Ordinal | Parameters | Result | Error |
    |---|---|---|---|---|---|---|

    """
  for m in p.methods {
    let kind = switch m.kind {
    case .call: "call"
    case .oneway: "one-way"
    case .event: "event"
    }
    let parameters = m.parameters.map { "`\($0.name): \($0.swiftType)`" }.joined(separator: ", ")
    out += "| `\(m.name)` | \(kind) | \(m.since) | `\(hex(m.ordinal))` | \(parameters.isEmpty ? "—" : parameters) "
      + "| \(m.result.map { "`\($0.swiftType)`" } ?? "—") | \(m.errorType.map { "`\($0)`" } ?? "—") |\n"
  }
  for m in p.methods {
    out += "\n## \(m.name)\n\n"
    out += layoutTable(m.kind == .event ? "Event body" : "Request body", m.request)
    if m.kind == .call { out += "\n" + layoutTable("Reply body", m.reply) }
  }
  let thrown = Set(p.methods.compactMap(\.errorType)).sorted()
  for name in thrown {
    guard let e = errors[name] else { continue }
    out += "\n## Errors: \(name)\n\n| Case | Code |\n|---|---|\n"
    for c in e.cases { out += "| `\(c.name)` | \(c.code) |\n" }
  }
  return out
}

func layoutTable(_ title: String, _ layout: Layout) -> String {
  guard !layout.fields.isEmpty else { return "\(title): empty.\n" }
  var out = "\(title), \(layout.size) bytes inline:\n\n| Offset | Size | Field | Type |\n|---|---|---|---|\n"
  for f in layout.fields {
    let name = f.name == "r" ? "result" : String(f.name.dropFirst(2))
    let type = switch f.type {
    case .integer(let t, _): t
    case .bool: "Bool"
    case .string: "String (count, presence; bytes out of line)"
    case .handle: "Handle (presence; handle in the side array)"
    }
    out += "| \(f.offset) | \(f.type.size) | `\(name)` | \(type) |\n"
  }
  return out
}
