// SPDX-License-Identifier: BSD-3-Clause
// Generated by abigen from lib/capi/gen/Todhchai.swift; don't edit.
//
// libtodhchai for Zig: `const td = @import("todhchai.zig");`, and link
// with -ltodhchai. Names drop the td_ prefix.


// MARK: Status and errors

/// 0 is success; errors are negative. The values are td_kernel.h's where they overlap.
pub const Status = i32;
// td_status values.
pub const OK: i32 = 0;
/// The system lacks something this needs (td_last_error names it).
pub const ERR_NOT_SUPPORTED: i32 = -2;
/// A NULL, a size too small for the struct, or a value out of range.
pub const ERR_INVALID_ARGS: i32 = -10;
/// The handle is stale or was never valid.
pub const ERR_BAD_HANDLE: i32 = -11;
/// Drawn for an older configuration: draw again for the newest (sdk.md §2).
pub const ERR_STALE_CONFIG: i32 = -40;
/// A system call failed (td_last_error has errno's text).
pub const ERR_IO: i32 = -41;
/// A file isn't in a format this reads.
pub const ERR_BAD_FORMAT: i32 = -42;
/// Why this thread's last call failed, or "". Valid until this thread's next call that fails.
pub extern fn td_last_error() [*c]const u8;
pub const last_error = td_last_error;

// MARK: Time

/// A deadline that never comes.
pub const FOREVER: u64 = 0xffffffffffffffff;
/// The monotonic clock, in nanoseconds.
pub extern fn td_now() u64;
pub const now = td_now;

// MARK: Handles

/// A window. {0, 0} is none.
pub const Window = extern struct {
    index: u32,
    generation: u32,
};
/// A decoded sound. {0, 0} is none.
pub const Sound = extern struct {
    index: u32,
    generation: u32,
};

// MARK: Events

// td_event.kind.
/// A timer's deadline came: `timer`.
pub const EV_TIMER: u16 = 1;
/// Reserved: watched handles join the C ABI later.
pub const EV_WATCH: u16 = 2;
/// A message posted to the loop: `message`.
pub const EV_MESSAGE: u16 = 3;
/// The loop was woken (td_loop_wake).
pub const EV_WAKE: u16 = 4;
/// The process was asked to stop (SIGINT, SIGTERM).
pub const EV_QUIT: u16 = 5;
/// A window's size, scale or state changed: `configure`.
pub const EV_CONFIGURE: u16 = 6;
/// The user asked to close a window.
pub const EV_CLOSE: u16 = 7;
/// Time to draw a window's next frame: `frame`.
pub const EV_FRAME: u16 = 8;
/// A key went down, or repeats: `key`.
pub const EV_KEY_DOWN: u16 = 9;
/// A key came up: `key`.
pub const EV_KEY_UP: u16 = 10;
/// The pointer entered, left, moved, or a button changed: `pointer`.
pub const EV_POINTER: u16 = 11;
/// A wheel or touchpad scrolled: `wheel`.
pub const EV_WHEEL: u16 = 12;
// td_configure_event.flags.
/// The window has keyboard focus.
pub const CONFIGURE_FOCUSED: u32 = 1;
/// An interactive resize is under way.
pub const CONFIGURE_RESIZING: u32 = 2;
/// TD_EV_CONFIGURE: draw for `config_seq`.
pub const ConfigureEvent = extern struct {
    /// Logical size.
    width: i32,
    height: i32,
    /// The size to draw at.
    pixel_width: i32,
    pixel_height: i32,
    /// Scale × 120 (120 is 1×).
    scale: u32,
    /// TD_CONFIGURE_*.
    flags: u32,
    /// Pass to td_present.
    config_seq: u64,
};
// td_frame_event.flags.
/// The target time is estimated, not from the display.
pub const FRAME_ESTIMATED: u32 = 1;
/// TD_EV_FRAME.
pub const FrameEvent = extern struct {
    frame_seq: u64,
    /// When this frame is expected on the glass (td_now's clock).
    target: u64,
    /// When the previous frame reached the glass; 0 if unknown.
    presented_at: u64,
    /// The display's refresh interval in ns; 0 if unknown.
    refresh: u64,
    /// TD_FRAME_*.
    flags: u32,
};
// Modifier bits.
pub const MOD_SHIFT: u8 = 1;
pub const MOD_CONTROL: u8 = 2;
pub const MOD_ALT: u8 = 4;
pub const MOD_SUPER: u8 = 8;
pub const MOD_CAPS_LOCK: u8 = 16;
pub const MOD_NUM_LOCK: u8 = 32;
/// TD_EV_KEY_DOWN, TD_EV_KEY_UP.
pub const KeyEvent = extern struct {
    /// The physical key: a HID keyboard usage, TD_KEY_*.
    usage: u16,
    /// TD_MOD_*.
    modifiers: u8,
    /// Held down and repeating.
    is_repeat: bool,
    /// The platform's code, for remapping UIs.
    scancode: u32,
};
// td_pointer_event.action.
pub const POINTER_ENTER: u8 = 1;
pub const POINTER_LEAVE: u8 = 2;
pub const POINTER_MOTION: u8 = 3;
pub const POINTER_DOWN: u8 = 4;
pub const POINTER_UP: u8 = 5;
// td_pointer_event.button; other buttons are the platform's code plus 256.
pub const BUTTON_LEFT: u32 = 1;
pub const BUTTON_RIGHT: u32 = 2;
pub const BUTTON_MIDDLE: u32 = 3;
pub const BUTTON_BACK: u32 = 4;
pub const BUTTON_FORWARD: u32 = 5;
/// TD_EV_POINTER.
pub const PointerEvent = extern struct {
    /// Position in logical units.
    x: f64,
    y: f64,
    /// TD_POINTER_*.
    action: u8,
    /// TD_MOD_*.
    modifiers: u8,
    /// For DOWN and UP: TD_BUTTON_*.
    button: u32,
};
/// TD_EV_WHEEL.
pub const WheelEvent = extern struct {
    /// Scroll distance in logical units.
    dx: f64,
    dy: f64,
    /// Wheel detents, where the device has them.
    steps_x: f64,
    steps_y: f64,
    /// TD_MOD_*.
    modifiers: u8,
};
/// TD_EV_TIMER.
pub const TimerEvent = extern struct {
    /// From td_timer_set.
    timer: u64,
    /// Repeats skipped because the loop was late.
    missed: u64,
};
/// TD_EV_MESSAGE.
pub const MessageEvent = extern struct {
    a: u64,
    b: u64,
};
/// The kind's data.
pub const EventPayload = extern union {
    configure: ConfigureEvent,
    frame: FrameEvent,
    key: KeyEvent,
    pointer: PointerEvent,
    wheel: WheelEvent,
    timer: TimerEvent,
    message: MessageEvent,
    bytes: [48]u8,
};
/// One event: 80 bytes (sdk.md §2).
pub const Event = extern struct {
    /// TD_EV_*.
    kind: u16,
    /// Reserved: 0.
    flags: u16,
    /// The window it's for, or {0, 0}.
    window: Window,
    /// When it was taken (td_now's clock).
    time: u64,
    /// Its place in the loop's sequence, from 1.
    seq: u64,
    payload: EventPayload,
};
/// The events one wait returned: valid until the next wait on the same loop.
pub const Events = extern struct {
    items: [*c]const Event,
    count: usize,
};

// MARK: The loop

/// A run loop: one per thread that waits.
pub const Loop = opaque {};
/// A loop for this thread, or NULL (td_last_error says why).
pub extern fn td_loop_create() ?*Loop;
pub const loop_create = td_loop_create;
/// Closes its windows and frees it.
pub extern fn td_loop_destroy(loop: ?*Loop) void;
pub const loop_destroy = td_loop_destroy;
/// Waits until there are events or `deadline`; frames come last in a batch.
pub extern fn td_loop_wait(loop: ?*Loop, deadline: u64, leeway: u64) Events;
pub const loop_wait = td_loop_wait;
/// The events ready now, without waiting.
pub extern fn td_loop_poll(loop: ?*Loop) Events;
pub const loop_poll = td_loop_poll;
/// Wakes the loop (TD_EV_WAKE), from any thread.
pub extern fn td_loop_wake(loop: ?*Loop) void;
pub const loop_wake = td_loop_wake;
/// Posts TD_EV_MESSAGE, from any thread.
pub extern fn td_loop_post(loop: ?*Loop, a: u64, b: u64) void;
pub const loop_post = td_loop_post;
/// A timer; TD_EV_TIMER carries the returned id.
pub extern fn td_timer_set(loop: ?*Loop, deadline: u64, leeway: u64, repeat: u64) u64;
pub const timer_set = td_timer_set;
/// Cancels a timer.
pub extern fn td_timer_cancel(loop: ?*Loop, timer: u64) void;
pub const timer_cancel = td_timer_cancel;

// MARK: Windows

/// A window to open (an input struct: set `size`).
pub const WindowDesc = extern struct {
    /// sizeof(td_window_desc).
    size: u32,
    /// Reserved: 0.
    flags: u32,
    title: [*c]const u8,
    /// Logical size.
    width: i32,
    height: i32,
};
/// Opens a window; {0, 0} on failure. TD_EV_CONFIGURE follows.
pub extern fn td_window_open(loop: ?*Loop, title: [*c]const u8, width: i32, height: i32) Window;
pub const window_open = td_window_open;
/// td_window_open, from a description.
pub extern fn td_window_open_desc(loop: ?*Loop, desc: [*c]const WindowDesc) Window;
pub const window_open_desc = td_window_open_desc;
/// Closes a window.
pub extern fn td_window_close(loop: ?*Loop, window: Window) void;
pub const window_close = td_window_close;
/// Asks for one TD_EV_FRAME, when it's time to draw.
pub extern fn td_frame_request(loop: ?*Loop, window: Window) void;
pub const frame_request = td_frame_request;
/// Pixels to draw into, XRGB8888 (an output struct).
pub const CpuSurface = extern struct {
    pixels: ?*anyopaque,
    width: i32,
    height: i32,
    /// Bytes a row.
    stride: u32,
    /// Frames since this buffer was last shown (0: never), for partial redraw.
    age: u32,
    window: Window,
    /// The SDK's own: leave it.
    buffer: u32,
    reserved: u32,
};
/// A surface for this frame; false before the first configure or while every buffer is on screen.
pub extern fn td_cpu_surface_acquire(loop: ?*Loop, window: Window, out: [*c]CpuSurface) bool;
pub const cpu_surface_acquire = td_cpu_surface_acquire;
/// Fills a surface with one color, 0x00RRGGBB.
pub extern fn td_fill(surface: [*c]const CpuSurface, xrgb: u32) void;
pub const fill = td_fill;
/// Shows a drawn surface. TD_ERR_STALE_CONFIG if drawn for an older configuration.
pub extern fn td_present(loop: ?*Loop, window: Window, surface: [*c]const CpuSurface, config_seq: u64) Status;
pub const present = td_present;

// MARK: Sound

/// Decodes a WAV file; {0, 0} on failure.
pub extern fn td_sound_load(path: [*c]const u8) Sound;
pub const sound_load = td_sound_load;
/// Frees a sound once no voice plays it.
pub extern fn td_sound_free(sound: Sound) void;
pub const sound_free = td_sound_free;
/// Plays a sound on the shared mixer; returns a voice, or 0 if it couldn't.
pub extern fn td_mixer_play(sound: Sound, gain: f32) u32;
pub const mixer_play = td_mixer_play;
/// Stops a voice.
pub extern fn td_mixer_stop(voice: u32) void;
pub const mixer_stop = td_mixer_stop;

// MARK: Keys: HID keyboard usages (lib/sdk/KeyUsage.swift)

pub const KEY_A: u16 = 4;
pub const KEY_B: u16 = 5;
pub const KEY_C: u16 = 6;
pub const KEY_D: u16 = 7;
pub const KEY_E: u16 = 8;
pub const KEY_F: u16 = 9;
pub const KEY_G: u16 = 10;
pub const KEY_H: u16 = 11;
pub const KEY_I: u16 = 12;
pub const KEY_J: u16 = 13;
pub const KEY_K: u16 = 14;
pub const KEY_L: u16 = 15;
pub const KEY_M: u16 = 16;
pub const KEY_N: u16 = 17;
pub const KEY_O: u16 = 18;
pub const KEY_P: u16 = 19;
pub const KEY_Q: u16 = 20;
pub const KEY_R: u16 = 21;
pub const KEY_S: u16 = 22;
pub const KEY_T: u16 = 23;
pub const KEY_U: u16 = 24;
pub const KEY_V: u16 = 25;
pub const KEY_W: u16 = 26;
pub const KEY_X: u16 = 27;
pub const KEY_Y: u16 = 28;
pub const KEY_Z: u16 = 29;
pub const KEY_DIGIT1: u16 = 30;
pub const KEY_DIGIT2: u16 = 31;
pub const KEY_DIGIT3: u16 = 32;
pub const KEY_DIGIT4: u16 = 33;
pub const KEY_DIGIT5: u16 = 34;
pub const KEY_DIGIT6: u16 = 35;
pub const KEY_DIGIT7: u16 = 36;
pub const KEY_DIGIT8: u16 = 37;
pub const KEY_DIGIT9: u16 = 38;
pub const KEY_DIGIT0: u16 = 39;
pub const KEY_ENTER: u16 = 40;
pub const KEY_ESCAPE: u16 = 41;
pub const KEY_BACKSPACE: u16 = 42;
pub const KEY_TAB: u16 = 43;
pub const KEY_SPACE: u16 = 44;
pub const KEY_MINUS: u16 = 45;
pub const KEY_EQUAL: u16 = 46;
pub const KEY_LEFT_BRACKET: u16 = 47;
pub const KEY_RIGHT_BRACKET: u16 = 48;
pub const KEY_BACKSLASH: u16 = 49;
pub const KEY_NON_US_HASH: u16 = 50;
pub const KEY_SEMICOLON: u16 = 51;
pub const KEY_APOSTROPHE: u16 = 52;
pub const KEY_GRAVE: u16 = 53;
pub const KEY_COMMA: u16 = 54;
pub const KEY_PERIOD: u16 = 55;
pub const KEY_SLASH: u16 = 56;
pub const KEY_CAPS_LOCK: u16 = 57;
pub const KEY_F1: u16 = 58;
pub const KEY_F2: u16 = 59;
pub const KEY_F3: u16 = 60;
pub const KEY_F4: u16 = 61;
pub const KEY_F5: u16 = 62;
pub const KEY_F6: u16 = 63;
pub const KEY_F7: u16 = 64;
pub const KEY_F8: u16 = 65;
pub const KEY_F9: u16 = 66;
pub const KEY_F10: u16 = 67;
pub const KEY_F11: u16 = 68;
pub const KEY_F12: u16 = 69;
pub const KEY_PRINT_SCREEN: u16 = 70;
pub const KEY_SCROLL_LOCK: u16 = 71;
pub const KEY_PAUSE: u16 = 72;
pub const KEY_INSERT: u16 = 73;
pub const KEY_HOME: u16 = 74;
pub const KEY_PAGE_UP: u16 = 75;
pub const KEY_DELETE: u16 = 76;
pub const KEY_END: u16 = 77;
pub const KEY_PAGE_DOWN: u16 = 78;
pub const KEY_RIGHT: u16 = 79;
pub const KEY_LEFT: u16 = 80;
pub const KEY_DOWN: u16 = 81;
pub const KEY_UP: u16 = 82;
pub const KEY_NUM_LOCK: u16 = 83;
pub const KEY_KEYPAD_SLASH: u16 = 84;
pub const KEY_KEYPAD_ASTERISK: u16 = 85;
pub const KEY_KEYPAD_MINUS: u16 = 86;
pub const KEY_KEYPAD_PLUS: u16 = 87;
pub const KEY_KEYPAD_ENTER: u16 = 88;
pub const KEY_KEYPAD1: u16 = 89;
pub const KEY_KEYPAD2: u16 = 90;
pub const KEY_KEYPAD3: u16 = 91;
pub const KEY_KEYPAD4: u16 = 92;
pub const KEY_KEYPAD5: u16 = 93;
pub const KEY_KEYPAD6: u16 = 94;
pub const KEY_KEYPAD7: u16 = 95;
pub const KEY_KEYPAD8: u16 = 96;
pub const KEY_KEYPAD9: u16 = 97;
pub const KEY_KEYPAD0: u16 = 98;
pub const KEY_KEYPAD_PERIOD: u16 = 99;
pub const KEY_NON_US_BACKSLASH: u16 = 100;
pub const KEY_APPLICATION: u16 = 101;
pub const KEY_POWER: u16 = 102;
pub const KEY_KEYPAD_EQUAL: u16 = 103;
pub const KEY_F13: u16 = 104;
pub const KEY_F14: u16 = 105;
pub const KEY_F15: u16 = 106;
pub const KEY_F16: u16 = 107;
pub const KEY_F17: u16 = 108;
pub const KEY_F18: u16 = 109;
pub const KEY_F19: u16 = 110;
pub const KEY_F20: u16 = 111;
pub const KEY_F21: u16 = 112;
pub const KEY_F22: u16 = 113;
pub const KEY_F23: u16 = 114;
pub const KEY_F24: u16 = 115;
pub const KEY_MUTE: u16 = 127;
pub const KEY_VOLUME_UP: u16 = 128;
pub const KEY_VOLUME_DOWN: u16 = 129;
pub const KEY_KEYPAD_COMMA: u16 = 133;
pub const KEY_LEFT_CONTROL: u16 = 224;
pub const KEY_LEFT_SHIFT: u16 = 225;
pub const KEY_LEFT_ALT: u16 = 226;
pub const KEY_LEFT_SUPER: u16 = 227;
pub const KEY_RIGHT_CONTROL: u16 = 228;
pub const KEY_RIGHT_SHIFT: u16 = 229;
pub const KEY_RIGHT_ALT: u16 = 230;
pub const KEY_RIGHT_SUPER: u16 = 231;

// MARK: Layouts (as abigen computed them)

comptime {
    if (@sizeOf(Window) != 8) @compileError("Window size");
    if (@offsetOf(Window, "index") != 0) @compileError("Window.index");
    if (@offsetOf(Window, "generation") != 4) @compileError("Window.generation");
    if (@sizeOf(Sound) != 8) @compileError("Sound size");
    if (@offsetOf(Sound, "index") != 0) @compileError("Sound.index");
    if (@offsetOf(Sound, "generation") != 4) @compileError("Sound.generation");
    if (@sizeOf(ConfigureEvent) != 32) @compileError("ConfigureEvent size");
    if (@offsetOf(ConfigureEvent, "width") != 0) @compileError("ConfigureEvent.width");
    if (@offsetOf(ConfigureEvent, "height") != 4) @compileError("ConfigureEvent.height");
    if (@offsetOf(ConfigureEvent, "pixel_width") != 8) @compileError("ConfigureEvent.pixel_width");
    if (@offsetOf(ConfigureEvent, "pixel_height") != 12) @compileError("ConfigureEvent.pixel_height");
    if (@offsetOf(ConfigureEvent, "scale") != 16) @compileError("ConfigureEvent.scale");
    if (@offsetOf(ConfigureEvent, "flags") != 20) @compileError("ConfigureEvent.flags");
    if (@offsetOf(ConfigureEvent, "config_seq") != 24) @compileError("ConfigureEvent.config_seq");
    if (@sizeOf(FrameEvent) != 40) @compileError("FrameEvent size");
    if (@offsetOf(FrameEvent, "frame_seq") != 0) @compileError("FrameEvent.frame_seq");
    if (@offsetOf(FrameEvent, "target") != 8) @compileError("FrameEvent.target");
    if (@offsetOf(FrameEvent, "presented_at") != 16) @compileError("FrameEvent.presented_at");
    if (@offsetOf(FrameEvent, "refresh") != 24) @compileError("FrameEvent.refresh");
    if (@offsetOf(FrameEvent, "flags") != 32) @compileError("FrameEvent.flags");
    if (@sizeOf(KeyEvent) != 8) @compileError("KeyEvent size");
    if (@offsetOf(KeyEvent, "usage") != 0) @compileError("KeyEvent.usage");
    if (@offsetOf(KeyEvent, "modifiers") != 2) @compileError("KeyEvent.modifiers");
    if (@offsetOf(KeyEvent, "is_repeat") != 3) @compileError("KeyEvent.is_repeat");
    if (@offsetOf(KeyEvent, "scancode") != 4) @compileError("KeyEvent.scancode");
    if (@sizeOf(PointerEvent) != 24) @compileError("PointerEvent size");
    if (@offsetOf(PointerEvent, "x") != 0) @compileError("PointerEvent.x");
    if (@offsetOf(PointerEvent, "y") != 8) @compileError("PointerEvent.y");
    if (@offsetOf(PointerEvent, "action") != 16) @compileError("PointerEvent.action");
    if (@offsetOf(PointerEvent, "modifiers") != 17) @compileError("PointerEvent.modifiers");
    if (@offsetOf(PointerEvent, "button") != 20) @compileError("PointerEvent.button");
    if (@sizeOf(WheelEvent) != 40) @compileError("WheelEvent size");
    if (@offsetOf(WheelEvent, "dx") != 0) @compileError("WheelEvent.dx");
    if (@offsetOf(WheelEvent, "dy") != 8) @compileError("WheelEvent.dy");
    if (@offsetOf(WheelEvent, "steps_x") != 16) @compileError("WheelEvent.steps_x");
    if (@offsetOf(WheelEvent, "steps_y") != 24) @compileError("WheelEvent.steps_y");
    if (@offsetOf(WheelEvent, "modifiers") != 32) @compileError("WheelEvent.modifiers");
    if (@sizeOf(TimerEvent) != 16) @compileError("TimerEvent size");
    if (@offsetOf(TimerEvent, "timer") != 0) @compileError("TimerEvent.timer");
    if (@offsetOf(TimerEvent, "missed") != 8) @compileError("TimerEvent.missed");
    if (@sizeOf(MessageEvent) != 16) @compileError("MessageEvent size");
    if (@offsetOf(MessageEvent, "a") != 0) @compileError("MessageEvent.a");
    if (@offsetOf(MessageEvent, "b") != 8) @compileError("MessageEvent.b");
    if (@sizeOf(EventPayload) != 48) @compileError("EventPayload size");
    if (@sizeOf(Event) != 80) @compileError("Event size");
    if (@offsetOf(Event, "kind") != 0) @compileError("Event.kind");
    if (@offsetOf(Event, "flags") != 2) @compileError("Event.flags");
    if (@offsetOf(Event, "window") != 4) @compileError("Event.window");
    if (@offsetOf(Event, "time") != 16) @compileError("Event.time");
    if (@offsetOf(Event, "seq") != 24) @compileError("Event.seq");
    if (@offsetOf(Event, "payload") != 32) @compileError("Event.payload");
    if (@sizeOf(Events) != 16) @compileError("Events size");
    if (@offsetOf(Events, "items") != 0) @compileError("Events.items");
    if (@offsetOf(Events, "count") != 8) @compileError("Events.count");
    if (@sizeOf(WindowDesc) != 24) @compileError("WindowDesc size");
    if (@offsetOf(WindowDesc, "size") != 0) @compileError("WindowDesc.size");
    if (@offsetOf(WindowDesc, "flags") != 4) @compileError("WindowDesc.flags");
    if (@offsetOf(WindowDesc, "title") != 8) @compileError("WindowDesc.title");
    if (@offsetOf(WindowDesc, "width") != 16) @compileError("WindowDesc.width");
    if (@offsetOf(WindowDesc, "height") != 20) @compileError("WindowDesc.height");
    if (@sizeOf(CpuSurface) != 40) @compileError("CpuSurface size");
    if (@offsetOf(CpuSurface, "pixels") != 0) @compileError("CpuSurface.pixels");
    if (@offsetOf(CpuSurface, "width") != 8) @compileError("CpuSurface.width");
    if (@offsetOf(CpuSurface, "height") != 12) @compileError("CpuSurface.height");
    if (@offsetOf(CpuSurface, "stride") != 16) @compileError("CpuSurface.stride");
    if (@offsetOf(CpuSurface, "age") != 20) @compileError("CpuSurface.age");
    if (@offsetOf(CpuSurface, "window") != 24) @compileError("CpuSurface.window");
    if (@offsetOf(CpuSurface, "buffer") != 32) @compileError("CpuSurface.buffer");
    if (@offsetOf(CpuSurface, "reserved") != 36) @compileError("CpuSurface.reserved");
}
