// SPDX-License-Identifier: BSD-3-Clause
//
// Generated by idlc from lib/fs/Fs.swift. Do not edit.
//
// Library todhchai.fs, version 1: the client side in C.
// Strings are pointer plus length (UTF-8, not NUL-terminated); optional
// values are pointers, NULL when absent (TD_HANDLE_INVALID for handles).
// What a reply returns points into the message buffer the call was
// given, and into the arena for vectors' elements and optional values.

#ifndef FS_IPC_IDL_H
#define FS_IPC_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <td_wire.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ATTRIBUTES_PROTOCOL_ID "todhchai.fs.Attributes"
#define ATTRIBUTES_VERSION 1
#define ATTRIBUTES_GET_ATTRIBUTE_ORDINAL UINT64_C(0x2ca0baeeb0f8ab9)
#define ATTRIBUTES_SET_ATTRIBUTE_ORDINAL UINT64_C(0x696558d602cd97bd)
#define ATTRIBUTES_REMOVE_ATTRIBUTE_ORDINAL UINT64_C(0x1329a1e5035dacab)

#define FILE_PROTOCOL_ID "todhchai.fs.File"
#define FILE_VERSION 1
#define FILE_RESIZE_ORDINAL UINT64_C(0x7e358fbfb2bdd1ec)
#define FILE_SYNC_ORDINAL UINT64_C(0x6af7afe4d60b1877)
// File composes NodeIPC.Node, Attributes: their functions work on its channels too.

#define DIRECTORY_PROTOCOL_ID "todhchai.fs.Directory"
#define DIRECTORY_VERSION 1
#define DIRECTORY_LIST_ORDINAL UINT64_C(0x7aa55dada472247b)
#define DIRECTORY_RENAME_ORDINAL UINT64_C(0x5477442b412d0849)
#define DIRECTORY_QUERY_ORDINAL UINT64_C(0x46f2a71dfd0306e1)
#define DIRECTORY_LIVE_ORDINAL UINT64_C(0x7a9450ada4639b31)
#define DIRECTORY_DECLARE_INDEX_ORDINAL UINT64_C(0x62bce3b7e41a456d)
#define DIRECTORY_INDICES_ORDINAL UINT64_C(0x31b984bf2bd0ebb0)
#define DIRECTORY_SYNC_ORDINAL UINT64_C(0x6bd699ad147783e4)
// Directory composes NodeIPC.Node, Attributes: their functions work on its channels too.

#define LIVE_QUERY_PROTOCOL_ID "todhchai.fs.LiveQuery"
#define LIVE_QUERY_VERSION 1
#define LIVE_QUERY_CHANGED_ORDINAL UINT64_C(0x5e4361104e220db0)

// FsError: codes in error replies (td_wire_call returns TD_ERR_REMOTE).
#define FS_ERROR_NOT_FOUND 1
#define FS_ERROR_EXISTS 2
#define FS_ERROR_NOT_DIRECTORY 3
#define FS_ERROR_IS_DIRECTORY 4
#define FS_ERROR_NOT_EMPTY 5
#define FS_ERROR_BAD_NAME 6
#define FS_ERROR_INVALID 7
#define FS_ERROR_NO_SPACE 8
#define FS_ERROR_READ_ONLY 9
#define FS_ERROR_IO 10
#define FS_ERROR_BAD_QUERY 11
#define FS_ERROR_NEEDS_INDEX 12
#define FS_ERROR_TOO_LARGE 13

// enum QueryChangeKind (UInt8): receivers reject other values.
typedef uint8_t fs_ipc_query_change_kind_t;
#define FS_IPC_QUERY_CHANGE_KIND_ADDED ((fs_ipc_query_change_kind_t)1)
#define FS_IPC_QUERY_CHANGE_KIND_REMOVED ((fs_ipc_query_change_kind_t)2)
#define FS_IPC_QUERY_CHANGE_KIND_CHANGED ((fs_ipc_query_change_kind_t)3)
#define FS_IPC_QUERY_CHANGE_KIND_CURRENT ((fs_ipc_query_change_kind_t)4)
#define FS_IPC_QUERY_CHANGE_KIND_RESET ((fs_ipc_query_change_kind_t)5)
static inline int fs_ipc_query_change_kind_known(uint64_t v) { return v == UINT64_C(1) || v == UINT64_C(2) || v == UINT64_C(3) || v == UINT64_C(4) || v == UINT64_C(5); }

typedef struct fs_ipc_attribute fs_ipc_attribute_t;
typedef struct fs_ipc_entry fs_ipc_entry_t;
typedef struct fs_ipc_listing fs_ipc_listing_t;
typedef struct fs_ipc_match fs_ipc_match_t;
typedef struct fs_ipc_query_change fs_ipc_query_change_t;
typedef struct fs_ipc_index_info fs_ipc_index_info_t;

typedef struct fs_ipc_vec_attribute {
  const fs_ipc_attribute_t *items;
  uint32_t count;
} fs_ipc_vec_attribute_t;

typedef struct fs_ipc_vec_entry {
  const fs_ipc_entry_t *items;
  uint32_t count;
} fs_ipc_vec_entry_t;

typedef struct fs_ipc_vec_str {
  const td_wire_str_t *items;
  uint32_t count;
} fs_ipc_vec_str_t;

typedef struct fs_ipc_vec_match {
  const fs_ipc_match_t *items;
  uint32_t count;
} fs_ipc_vec_match_t;

typedef struct fs_ipc_vec_index_info {
  const fs_ipc_index_info_t *items;
  uint32_t count;
} fs_ipc_vec_index_info_t;

struct fs_ipc_attribute {
  td_wire_str_t name;
  uint8_t kind;
  td_wire_bytes_t value;
};

struct fs_ipc_entry {
  td_wire_str_t name;
  uint64_t node;
  uint8_t kind;
  uint64_t size;
  int64_t modified;
  fs_ipc_vec_attribute_t attributes;
};

struct fs_ipc_listing {
  fs_ipc_vec_entry_t entries;
  uint64_t next;
  bool done;
};

struct fs_ipc_match {
  uint64_t node;
  td_wire_str_t path;
};

struct fs_ipc_query_change {
  fs_ipc_query_change_kind_t kind;
  uint64_t node;
  td_wire_str_t path;
  uint64_t seq;
};

struct fs_ipc_index_info {
  td_wire_str_t name;
  uint8_t kind;
  bool caseless;
  bool building;
};

static inline td_status_t fs_ipc_attribute_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_attribute_t *in);
static inline td_status_t fs_ipc_attribute_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_attribute_t *out);
static inline td_status_t fs_ipc_entry_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_entry_t *in);
static inline td_status_t fs_ipc_entry_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_entry_t *out);
static inline td_status_t fs_ipc_listing_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_listing_t *in);
static inline td_status_t fs_ipc_listing_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_listing_t *out);
static inline td_status_t fs_ipc_match_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_match_t *in);
static inline td_status_t fs_ipc_match_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_match_t *out);
static inline td_status_t fs_ipc_query_change_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_query_change_t *in);
static inline td_status_t fs_ipc_query_change_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_query_change_t *out);
static inline td_status_t fs_ipc_index_info_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_index_info_t *in);
static inline td_status_t fs_ipc_index_info_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_index_info_t *out);

static inline td_status_t fs_ipc_attribute_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_attribute_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = td_wire_store_bytes(m, o + 0, (in->name).data, (in->name).len)) != TD_OK) return s;
  td_wire_store(m, o + 16, (uint64_t)(in->kind), 1);
  if ((s = td_wire_store_bytes(m, o + 24, (in->value).data, (in->value).len)) != TD_OK) return s;
  return TD_OK;
}

static inline td_status_t fs_ipc_attribute_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_attribute_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 17, 7) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_string(r, o + 0, &(out->name).data, &(out->name).len) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 16, 1, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->kind = (uint8_t)(uint8_t)v;
  if (td_wire_load_bytes(r, o + 24, &(out->value).data, &(out->value).len) != TD_OK) return TD_ERR_PROTOCOL;
  return TD_OK;
}

static inline td_status_t fs_ipc_entry_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_entry_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = td_wire_store_bytes(m, o + 0, (in->name).data, (in->name).len)) != TD_OK) return s;
  td_wire_store(m, o + 16, (uint64_t)(in->node), 8);
  td_wire_store(m, o + 24, (uint64_t)(in->kind), 1);
  td_wire_store(m, o + 32, (uint64_t)(in->size), 8);
  td_wire_store(m, o + 40, (uint64_t)(in->modified), 8);
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, o + 48, (in->attributes).count, 40, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (in->attributes).count; i0++) {
  if ((s = fs_ipc_attribute_encode(m, b0 + i0 * 40, &((in->attributes).items[i0]))) != TD_OK) return s;
  }
  }
  return TD_OK;
}

static inline td_status_t fs_ipc_entry_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_entry_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 25, 7) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_string(r, o + 0, &(out->name).data, &(out->name).len) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 16, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->node = (uint64_t)(uint64_t)v;
  if (td_wire_load(r, o + 24, 1, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->kind = (uint8_t)(uint8_t)v;
  if (td_wire_load(r, o + 32, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->size = (uint64_t)(uint64_t)v;
  if (td_wire_load(r, o + 40, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->modified = (int64_t)(uint64_t)v;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, o + 48, 40, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  fs_ipc_attribute_t *e0 = (fs_ipc_attribute_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(fs_ipc_attribute_t), (uint32_t)_Alignof(fs_ipc_attribute_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if ((s = fs_ipc_attribute_decode(r, b0 + i0 * 40, a, &(e0[i0]))) != TD_OK) return s;
  }
  (out->attributes).items = (const fs_ipc_attribute_t *)e0;
  (out->attributes).count = n0;
  }
  return TD_OK;
}

static inline td_status_t fs_ipc_listing_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_listing_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, o + 0, (in->entries).count, 64, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (in->entries).count; i0++) {
  if ((s = fs_ipc_entry_encode(m, b0 + i0 * 64, &((in->entries).items[i0]))) != TD_OK) return s;
  }
  }
  td_wire_store(m, o + 16, (uint64_t)(in->next), 8);
  td_wire_store(m, o + 24, (in->done) ? 1 : 0, 1);
  return TD_OK;
}

static inline td_status_t fs_ipc_listing_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_listing_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 25, 7) != TD_OK) return TD_ERR_PROTOCOL;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, o + 0, 64, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  fs_ipc_entry_t *e0 = (fs_ipc_entry_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(fs_ipc_entry_t), (uint32_t)_Alignof(fs_ipc_entry_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if ((s = fs_ipc_entry_decode(r, b0 + i0 * 64, a, &(e0[i0]))) != TD_OK) return s;
  }
  (out->entries).items = (const fs_ipc_entry_t *)e0;
  (out->entries).count = n0;
  }
  if (td_wire_load(r, o + 16, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->next = (uint64_t)(uint64_t)v;
  { uint8_t b; if (td_wire_load_bool(r, o + 24, &b) != TD_OK) return TD_ERR_PROTOCOL; out->done = b; }
  return TD_OK;
}

static inline td_status_t fs_ipc_match_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_match_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  td_wire_store(m, o + 0, (uint64_t)(in->node), 8);
  if ((s = td_wire_store_bytes(m, o + 8, (in->path).data, (in->path).len)) != TD_OK) return s;
  return TD_OK;
}

static inline td_status_t fs_ipc_match_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_match_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_load(r, o + 0, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->node = (uint64_t)(uint64_t)v;
  if (td_wire_load_string(r, o + 8, &(out->path).data, &(out->path).len) != TD_OK) return TD_ERR_PROTOCOL;
  return TD_OK;
}

static inline td_status_t fs_ipc_query_change_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_query_change_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  td_wire_store(m, o + 0, (uint64_t)(in->kind), 1);
  td_wire_store(m, o + 8, (uint64_t)(in->node), 8);
  if ((s = td_wire_store_bytes(m, o + 16, (in->path).data, (in->path).len)) != TD_OK) return s;
  td_wire_store(m, o + 32, (uint64_t)(in->seq), 8);
  return TD_OK;
}

static inline td_status_t fs_ipc_query_change_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_query_change_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 1, 7) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 0, 1, &v) != TD_OK || !fs_ipc_query_change_kind_known(v)) return TD_ERR_PROTOCOL;
  out->kind = (fs_ipc_query_change_kind_t)(uint8_t)v;
  if (td_wire_load(r, o + 8, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->node = (uint64_t)(uint64_t)v;
  if (td_wire_load_string(r, o + 16, &(out->path).data, &(out->path).len) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 32, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->seq = (uint64_t)(uint64_t)v;
  return TD_OK;
}

static inline td_status_t fs_ipc_index_info_encode(td_wire_msg_t *m, uint32_t o, const fs_ipc_index_info_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = td_wire_store_bytes(m, o + 0, (in->name).data, (in->name).len)) != TD_OK) return s;
  td_wire_store(m, o + 16, (uint64_t)(in->kind), 1);
  td_wire_store(m, o + 17, (in->caseless) ? 1 : 0, 1);
  td_wire_store(m, o + 18, (in->building) ? 1 : 0, 1);
  return TD_OK;
}

static inline td_status_t fs_ipc_index_info_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, fs_ipc_index_info_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 19, 5) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_string(r, o + 0, &(out->name).data, &(out->name).len) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 16, 1, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->kind = (uint8_t)(uint8_t)v;
  { uint8_t b; if (td_wire_load_bool(r, o + 17, &b) != TD_OK) return TD_ERR_PROTOCOL; out->caseless = b; }
  { uint8_t b; if (td_wire_load_bool(r, o + 18, &b) != TD_OK) return TD_ERR_PROTOCOL; out->building = b; }
  return TD_OK;
}

// getAttribute: encodes the request. txid is the caller's, nonzero.
static inline td_status_t attributes_get_attribute_encode(td_wire_msg_t *m, uint32_t txid, const char *name, uint32_t name_len) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, ATTRIBUTES_GET_ATTRIBUTE_ORDINAL, 16);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ name, name_len })).data, (((td_wire_str_t){ name, name_len })).len)) != TD_OK) return s;
  return TD_OK;
}

// getAttribute: decodes the reply.
static inline td_status_t attributes_get_attribute_decode_reply(const td_wire_msg_t *m, fs_ipc_attribute_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 40) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = fs_ipc_attribute_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// getAttribute: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t attributes_get_attribute(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *name, uint32_t name_len, fs_ipc_attribute_t *result) {
  td_status_t s = attributes_get_attribute_encode(buf, txid, name, name_len);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return attributes_get_attribute_decode_reply(buf, result);
}

// setAttribute: encodes the request. txid is the caller's, nonzero.
static inline td_status_t attributes_set_attribute_encode(td_wire_msg_t *m, uint32_t txid, const fs_ipc_attribute_t *attribute) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, ATTRIBUTES_SET_ATTRIBUTE_ORDINAL, 40);
  if (s != TD_OK) return s;
  if ((s = fs_ipc_attribute_encode(m, 0, &((*attribute)))) != TD_OK) return s;
  return TD_OK;
}

// setAttribute: decodes the reply.
static inline td_status_t attributes_set_attribute_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// setAttribute: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t attributes_set_attribute(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const fs_ipc_attribute_t *attribute) {
  td_status_t s = attributes_set_attribute_encode(buf, txid, attribute);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return attributes_set_attribute_decode_reply(buf);
}

// removeAttribute: encodes the request. txid is the caller's, nonzero.
static inline td_status_t attributes_remove_attribute_encode(td_wire_msg_t *m, uint32_t txid, const char *name, uint32_t name_len) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, ATTRIBUTES_REMOVE_ATTRIBUTE_ORDINAL, 16);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ name, name_len })).data, (((td_wire_str_t){ name, name_len })).len)) != TD_OK) return s;
  return TD_OK;
}

// removeAttribute: decodes the reply.
static inline td_status_t attributes_remove_attribute_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// removeAttribute: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t attributes_remove_attribute(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *name, uint32_t name_len) {
  td_status_t s = attributes_remove_attribute_encode(buf, txid, name, name_len);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return attributes_remove_attribute_decode_reply(buf);
}

// resize: encodes the request. txid is the caller's, nonzero.
static inline td_status_t file_resize_encode(td_wire_msg_t *m, uint32_t txid, uint64_t size) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, FILE_RESIZE_ORDINAL, 8);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(size), 8);
  return TD_OK;
}

// resize: decodes the reply.
static inline td_status_t file_resize_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// resize: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t file_resize(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint64_t size) {
  td_status_t s = file_resize_encode(buf, txid, size);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return file_resize_decode_reply(buf);
}

// sync: encodes the request. txid is the caller's, nonzero.
static inline td_status_t file_sync_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, FILE_SYNC_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// sync: decodes the reply.
static inline td_status_t file_sync_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// sync: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t file_sync(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code) {
  td_status_t s = file_sync_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return file_sync_decode_reply(buf);
}

// list: encodes the request. txid is the caller's, nonzero.
static inline td_status_t directory_list_encode(td_wire_msg_t *m, uint32_t txid, uint64_t cursor, uint32_t max, fs_ipc_vec_str_t attributes) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DIRECTORY_LIST_ORDINAL, 32);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(cursor), 8);
  td_wire_store(m, 8, (uint64_t)(max), 4);
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, 16, (attributes).count, 16, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (attributes).count; i0++) {
  if ((s = td_wire_store_bytes(m, b0 + i0 * 16, ((attributes).items[i0]).data, ((attributes).items[i0]).len)) != TD_OK) return s;
  }
  }
  return TD_OK;
}

// list: decodes the reply.
static inline td_status_t directory_list_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, fs_ipc_listing_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 32) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = fs_ipc_listing_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// list: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t directory_list(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint64_t cursor, uint32_t max, fs_ipc_vec_str_t attributes, td_wire_arena_t *arena, fs_ipc_listing_t *result) {
  td_status_t s = directory_list_encode(buf, txid, cursor, max, attributes);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return directory_list_decode_reply(buf, arena, result);
}

// rename: encodes the request. txid is the caller's, nonzero.
static inline td_status_t directory_rename_encode(td_wire_msg_t *m, uint32_t txid, const char *from, uint32_t from_len, const char *to, uint32_t to_len) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DIRECTORY_RENAME_ORDINAL, 32);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ from, from_len })).data, (((td_wire_str_t){ from, from_len })).len)) != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 16, (((td_wire_str_t){ to, to_len })).data, (((td_wire_str_t){ to, to_len })).len)) != TD_OK) return s;
  return TD_OK;
}

// rename: decodes the reply.
static inline td_status_t directory_rename_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// rename: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t directory_rename(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *from, uint32_t from_len, const char *to, uint32_t to_len) {
  td_status_t s = directory_rename_encode(buf, txid, from, from_len, to, to_len);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return directory_rename_decode_reply(buf);
}

// query: encodes the request. txid is the caller's, nonzero.
static inline td_status_t directory_query_encode(td_wire_msg_t *m, uint32_t txid, const char *text, uint32_t text_len, bool scan) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DIRECTORY_QUERY_ORDINAL, 24);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ text, text_len })).data, (((td_wire_str_t){ text, text_len })).len)) != TD_OK) return s;
  td_wire_store(m, 16, (scan) ? 1 : 0, 1);
  return TD_OK;
}

// query: decodes the reply.
static inline td_status_t directory_query_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, fs_ipc_vec_match_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 16) != TD_OK) return TD_ERR_PROTOCOL;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, 0, 24, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  fs_ipc_match_t *e0 = (fs_ipc_match_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(fs_ipc_match_t), (uint32_t)_Alignof(fs_ipc_match_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if ((s = fs_ipc_match_decode(r, b0 + i0 * 24, a, &(e0[i0]))) != TD_OK) return s;
  }
  ((*result)).items = (const fs_ipc_match_t *)e0;
  ((*result)).count = n0;
  }
  return td_wire_read_end(r);
}

// query: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t directory_query(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *text, uint32_t text_len, bool scan, td_wire_arena_t *arena, fs_ipc_vec_match_t *result) {
  td_status_t s = directory_query_encode(buf, txid, text, text_len, scan);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return directory_query_decode_reply(buf, arena, result);
}

// live: encodes the request. txid is the caller's, nonzero.
static inline td_status_t directory_live_encode(td_wire_msg_t *m, uint32_t txid, const char *text, uint32_t text_len, bool scan) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DIRECTORY_LIVE_ORDINAL, 24);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ text, text_len })).data, (((td_wire_str_t){ text, text_len })).len)) != TD_OK) return s;
  td_wire_store(m, 16, (scan) ? 1 : 0, 1);
  return TD_OK;
}

// live: decodes the reply.
static inline td_status_t directory_live_decode_reply(const td_wire_msg_t *m, td_handle_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 8) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_check_padding(r, 4, 4) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_handle(r, 0, &((*result))) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// live: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t directory_live(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *text, uint32_t text_len, bool scan, td_handle_t *result) {
  td_status_t s = directory_live_encode(buf, txid, text, text_len, scan);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return directory_live_decode_reply(buf, result);
}

// declareIndex: encodes the request. txid is the caller's, nonzero.
static inline td_status_t directory_declare_index_encode(td_wire_msg_t *m, uint32_t txid, const char *name, uint32_t name_len, uint8_t kind, bool caseless) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DIRECTORY_DECLARE_INDEX_ORDINAL, 24);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ name, name_len })).data, (((td_wire_str_t){ name, name_len })).len)) != TD_OK) return s;
  td_wire_store(m, 16, (uint64_t)(kind), 1);
  td_wire_store(m, 17, (caseless) ? 1 : 0, 1);
  return TD_OK;
}

// declareIndex: decodes the reply.
static inline td_status_t directory_declare_index_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// declareIndex: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t directory_declare_index(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *name, uint32_t name_len, uint8_t kind, bool caseless) {
  td_status_t s = directory_declare_index_encode(buf, txid, name, name_len, kind, caseless);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return directory_declare_index_decode_reply(buf);
}

// indices: encodes the request. txid is the caller's, nonzero.
static inline td_status_t directory_indices_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DIRECTORY_INDICES_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// indices: decodes the reply.
static inline td_status_t directory_indices_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, fs_ipc_vec_index_info_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 16) != TD_OK) return TD_ERR_PROTOCOL;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, 0, 24, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  fs_ipc_index_info_t *e0 = (fs_ipc_index_info_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(fs_ipc_index_info_t), (uint32_t)_Alignof(fs_ipc_index_info_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if ((s = fs_ipc_index_info_decode(r, b0 + i0 * 24, a, &(e0[i0]))) != TD_OK) return s;
  }
  ((*result)).items = (const fs_ipc_index_info_t *)e0;
  ((*result)).count = n0;
  }
  return td_wire_read_end(r);
}

// indices: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t directory_indices(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, td_wire_arena_t *arena, fs_ipc_vec_index_info_t *result) {
  td_status_t s = directory_indices_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return directory_indices_decode_reply(buf, arena, result);
}

// sync: encodes the request. txid is the caller's, nonzero.
static inline td_status_t directory_sync_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, DIRECTORY_SYNC_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// sync: decodes the reply.
static inline td_status_t directory_sync_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// sync: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t directory_sync(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code) {
  td_status_t s = directory_sync_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return directory_sync_decode_reply(buf);
}

// changed (event): decodes it.
static inline td_status_t live_query_changed_decode(const td_wire_msg_t *m, fs_ipc_query_change_t *change) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 40) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = fs_ipc_query_change_decode(r, 0, a, &((*change)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

#ifdef __cplusplus
}
#endif

#endif
