// SPDX-License-Identifier: BSD-3-Clause
// Generated by abigen from lib/capi/gen/Todhchai.swift; don't edit.
//
// libtodhchai for Odin: `import td "todhchai"`. Names drop the td_ prefix.

package todhchai

foreign import lib "system:todhchai"

// MARK: Status and errors

// 0 is success; errors are negative. The values are td_kernel.h's where they overlap.
Status :: i32
// td_status values.
OK :: i32(0)
// The system lacks something this needs (td_last_error names it).
ERR_NOT_SUPPORTED :: i32(-2)
// A NULL, a size too small for the struct, or a value out of range.
ERR_INVALID_ARGS :: i32(-10)
// The handle is stale or was never valid.
ERR_BAD_HANDLE :: i32(-11)
// Drawn for an older configuration: draw again for the newest (sdk.md §2).
ERR_STALE_CONFIG :: i32(-40)
// A system call failed (td_last_error has errno's text).
ERR_IO :: i32(-41)
// A file isn't in a format this reads.
ERR_BAD_FORMAT :: i32(-42)

// MARK: Time

// A deadline that never comes.
FOREVER :: u64(0xffffffffffffffff)

// MARK: Handles

// A window. {0, 0} is none.
Window :: struct {
	index: u32,
	generation: u32,
}
// A decoded sound. {0, 0} is none.
Sound :: struct {
	index: u32,
	generation: u32,
}

// MARK: Events

// td_event.kind.
// A timer's deadline came: `timer`.
EV_TIMER :: u16(1)
// Reserved: watched handles join the C ABI later.
EV_WATCH :: u16(2)
// A message posted to the loop: `message`.
EV_MESSAGE :: u16(3)
// The loop was woken (td_loop_wake).
EV_WAKE :: u16(4)
// The process was asked to stop (SIGINT, SIGTERM).
EV_QUIT :: u16(5)
// A window's size, scale or state changed: `configure`.
EV_CONFIGURE :: u16(6)
// The user asked to close a window.
EV_CLOSE :: u16(7)
// Time to draw a window's next frame: `frame`.
EV_FRAME :: u16(8)
// A key went down, or repeats: `key`.
EV_KEY_DOWN :: u16(9)
// A key came up: `key`.
EV_KEY_UP :: u16(10)
// The pointer entered, left, moved, or a button changed: `pointer`.
EV_POINTER :: u16(11)
// A wheel or touchpad scrolled: `wheel`.
EV_WHEEL :: u16(12)
// td_configure_event.flags.
// The window has keyboard focus.
CONFIGURE_FOCUSED :: u32(1)
// An interactive resize is under way.
CONFIGURE_RESIZING :: u32(2)
// TD_EV_CONFIGURE: draw for `config_seq`.
Configure_Event :: struct {
	// Logical size.
	width: i32,
	height: i32,
	// The size to draw at.
	pixel_width: i32,
	pixel_height: i32,
	// Scale × 120 (120 is 1×).
	scale: u32,
	// TD_CONFIGURE_*.
	flags: u32,
	// Pass to td_present.
	config_seq: u64,
}
// td_frame_event.flags.
// The target time is estimated, not from the display.
FRAME_ESTIMATED :: u32(1)
// TD_EV_FRAME.
Frame_Event :: struct {
	frame_seq: u64,
	// When this frame is expected on the glass (td_now's clock).
	target: u64,
	// When the previous frame reached the glass; 0 if unknown.
	presented_at: u64,
	// The display's refresh interval in ns; 0 if unknown.
	refresh: u64,
	// TD_FRAME_*.
	flags: u32,
}
// Modifier bits.
MOD_SHIFT :: u8(1)
MOD_CONTROL :: u8(2)
MOD_ALT :: u8(4)
MOD_SUPER :: u8(8)
MOD_CAPS_LOCK :: u8(16)
MOD_NUM_LOCK :: u8(32)
// TD_EV_KEY_DOWN, TD_EV_KEY_UP.
Key_Event :: struct {
	// The physical key: a HID keyboard usage, TD_KEY_*.
	usage: u16,
	// TD_MOD_*.
	modifiers: u8,
	// Held down and repeating.
	is_repeat: bool,
	// The platform's code, for remapping UIs.
	scancode: u32,
}
// td_pointer_event.action.
POINTER_ENTER :: u8(1)
POINTER_LEAVE :: u8(2)
POINTER_MOTION :: u8(3)
POINTER_DOWN :: u8(4)
POINTER_UP :: u8(5)
// td_pointer_event.button; other buttons are the platform's code plus 256.
BUTTON_LEFT :: u32(1)
BUTTON_RIGHT :: u32(2)
BUTTON_MIDDLE :: u32(3)
BUTTON_BACK :: u32(4)
BUTTON_FORWARD :: u32(5)
// TD_EV_POINTER.
Pointer_Event :: struct {
	// Position in logical units.
	x: f64,
	y: f64,
	// TD_POINTER_*.
	action: u8,
	// TD_MOD_*.
	modifiers: u8,
	// For DOWN and UP: TD_BUTTON_*.
	button: u32,
}
// TD_EV_WHEEL.
Wheel_Event :: struct {
	// Scroll distance in logical units.
	dx: f64,
	dy: f64,
	// Wheel detents, where the device has them.
	steps_x: f64,
	steps_y: f64,
	// TD_MOD_*.
	modifiers: u8,
}
// TD_EV_TIMER.
Timer_Event :: struct {
	// From td_timer_set.
	timer: u64,
	// Repeats skipped because the loop was late.
	missed: u64,
}
// TD_EV_MESSAGE.
Message_Event :: struct {
	a: u64,
	b: u64,
}
// The kind's data.
Event_Payload :: struct #raw_union {
	configure: Configure_Event,
	frame: Frame_Event,
	key: Key_Event,
	pointer: Pointer_Event,
	wheel: Wheel_Event,
	timer: Timer_Event,
	message: Message_Event,
	bytes: [48]u8,
}
// One event: 80 bytes (sdk.md §2).
Event :: struct {
	// TD_EV_*.
	kind: u16,
	// Reserved: 0.
	flags: u16,
	// The window it's for, or {0, 0}.
	window: Window,
	// When it was taken (td_now's clock).
	time: u64,
	// Its place in the loop's sequence, from 1.
	seq: u64,
	using payload: Event_Payload,
}
// The events one wait returned: valid until the next wait on the same loop.
Events :: struct {
	items: [^]Event,
	count: uint,
}

// MARK: The loop

// A run loop: one per thread that waits.
Loop :: struct {}

// MARK: Windows

// A window to open (an input struct: set `size`).
Window_Desc :: struct {
	// sizeof(td_window_desc).
	size: u32,
	// Reserved: 0.
	flags: u32,
	title: cstring,
	// Logical size.
	width: i32,
	height: i32,
}
// Pixels to draw into, XRGB8888 (an output struct).
CPU_Surface :: struct {
	pixels: rawptr,
	width: i32,
	height: i32,
	// Bytes a row.
	stride: u32,
	// Frames since this buffer was last shown (0: never), for partial redraw.
	age: u32,
	window: Window,
	// The SDK's own: leave it.
	buffer: u32,
	reserved: u32,
}

// MARK: Sound


// MARK: Keys: HID keyboard usages (lib/sdk/KeyUsage.swift)

KEY_A :: u16(4)
KEY_B :: u16(5)
KEY_C :: u16(6)
KEY_D :: u16(7)
KEY_E :: u16(8)
KEY_F :: u16(9)
KEY_G :: u16(10)
KEY_H :: u16(11)
KEY_I :: u16(12)
KEY_J :: u16(13)
KEY_K :: u16(14)
KEY_L :: u16(15)
KEY_M :: u16(16)
KEY_N :: u16(17)
KEY_O :: u16(18)
KEY_P :: u16(19)
KEY_Q :: u16(20)
KEY_R :: u16(21)
KEY_S :: u16(22)
KEY_T :: u16(23)
KEY_U :: u16(24)
KEY_V :: u16(25)
KEY_W :: u16(26)
KEY_X :: u16(27)
KEY_Y :: u16(28)
KEY_Z :: u16(29)
KEY_DIGIT1 :: u16(30)
KEY_DIGIT2 :: u16(31)
KEY_DIGIT3 :: u16(32)
KEY_DIGIT4 :: u16(33)
KEY_DIGIT5 :: u16(34)
KEY_DIGIT6 :: u16(35)
KEY_DIGIT7 :: u16(36)
KEY_DIGIT8 :: u16(37)
KEY_DIGIT9 :: u16(38)
KEY_DIGIT0 :: u16(39)
KEY_ENTER :: u16(40)
KEY_ESCAPE :: u16(41)
KEY_BACKSPACE :: u16(42)
KEY_TAB :: u16(43)
KEY_SPACE :: u16(44)
KEY_MINUS :: u16(45)
KEY_EQUAL :: u16(46)
KEY_LEFT_BRACKET :: u16(47)
KEY_RIGHT_BRACKET :: u16(48)
KEY_BACKSLASH :: u16(49)
KEY_NON_US_HASH :: u16(50)
KEY_SEMICOLON :: u16(51)
KEY_APOSTROPHE :: u16(52)
KEY_GRAVE :: u16(53)
KEY_COMMA :: u16(54)
KEY_PERIOD :: u16(55)
KEY_SLASH :: u16(56)
KEY_CAPS_LOCK :: u16(57)
KEY_F1 :: u16(58)
KEY_F2 :: u16(59)
KEY_F3 :: u16(60)
KEY_F4 :: u16(61)
KEY_F5 :: u16(62)
KEY_F6 :: u16(63)
KEY_F7 :: u16(64)
KEY_F8 :: u16(65)
KEY_F9 :: u16(66)
KEY_F10 :: u16(67)
KEY_F11 :: u16(68)
KEY_F12 :: u16(69)
KEY_PRINT_SCREEN :: u16(70)
KEY_SCROLL_LOCK :: u16(71)
KEY_PAUSE :: u16(72)
KEY_INSERT :: u16(73)
KEY_HOME :: u16(74)
KEY_PAGE_UP :: u16(75)
KEY_DELETE :: u16(76)
KEY_END :: u16(77)
KEY_PAGE_DOWN :: u16(78)
KEY_RIGHT :: u16(79)
KEY_LEFT :: u16(80)
KEY_DOWN :: u16(81)
KEY_UP :: u16(82)
KEY_NUM_LOCK :: u16(83)
KEY_KEYPAD_SLASH :: u16(84)
KEY_KEYPAD_ASTERISK :: u16(85)
KEY_KEYPAD_MINUS :: u16(86)
KEY_KEYPAD_PLUS :: u16(87)
KEY_KEYPAD_ENTER :: u16(88)
KEY_KEYPAD1 :: u16(89)
KEY_KEYPAD2 :: u16(90)
KEY_KEYPAD3 :: u16(91)
KEY_KEYPAD4 :: u16(92)
KEY_KEYPAD5 :: u16(93)
KEY_KEYPAD6 :: u16(94)
KEY_KEYPAD7 :: u16(95)
KEY_KEYPAD8 :: u16(96)
KEY_KEYPAD9 :: u16(97)
KEY_KEYPAD0 :: u16(98)
KEY_KEYPAD_PERIOD :: u16(99)
KEY_NON_US_BACKSLASH :: u16(100)
KEY_APPLICATION :: u16(101)
KEY_POWER :: u16(102)
KEY_KEYPAD_EQUAL :: u16(103)
KEY_F13 :: u16(104)
KEY_F14 :: u16(105)
KEY_F15 :: u16(106)
KEY_F16 :: u16(107)
KEY_F17 :: u16(108)
KEY_F18 :: u16(109)
KEY_F19 :: u16(110)
KEY_F20 :: u16(111)
KEY_F21 :: u16(112)
KEY_F22 :: u16(113)
KEY_F23 :: u16(114)
KEY_F24 :: u16(115)
KEY_MUTE :: u16(127)
KEY_VOLUME_UP :: u16(128)
KEY_VOLUME_DOWN :: u16(129)
KEY_KEYPAD_COMMA :: u16(133)
KEY_LEFT_CONTROL :: u16(224)
KEY_LEFT_SHIFT :: u16(225)
KEY_LEFT_ALT :: u16(226)
KEY_LEFT_SUPER :: u16(227)
KEY_RIGHT_CONTROL :: u16(228)
KEY_RIGHT_SHIFT :: u16(229)
KEY_RIGHT_ALT :: u16(230)
KEY_RIGHT_SUPER :: u16(231)

// MARK: Functions

@(default_calling_convention = "c", link_prefix = "td_")
foreign lib {
	// Why this thread's last call failed, or "". Valid until this thread's next call that fails.
	last_error :: proc() -> cstring ---
	// The monotonic clock, in nanoseconds.
	now :: proc() -> u64 ---
	// A loop for this thread, or NULL (td_last_error says why).
	loop_create :: proc() -> ^Loop ---
	// Closes its windows and frees it.
	loop_destroy :: proc(loop: ^Loop) ---
	// Waits until there are events or `deadline`; frames come last in a batch.
	loop_wait :: proc(loop: ^Loop, deadline: u64, leeway: u64) -> Events ---
	// The events ready now, without waiting.
	loop_poll :: proc(loop: ^Loop) -> Events ---
	// Wakes the loop (TD_EV_WAKE), from any thread.
	loop_wake :: proc(loop: ^Loop) ---
	// Posts TD_EV_MESSAGE, from any thread.
	loop_post :: proc(loop: ^Loop, a: u64, b: u64) ---
	// A timer; TD_EV_TIMER carries the returned id.
	timer_set :: proc(loop: ^Loop, deadline: u64, leeway: u64, repeat: u64) -> u64 ---
	// Cancels a timer.
	timer_cancel :: proc(loop: ^Loop, timer: u64) ---
	// Opens a window; {0, 0} on failure. TD_EV_CONFIGURE follows.
	window_open :: proc(loop: ^Loop, title: cstring, width: i32, height: i32) -> Window ---
	// td_window_open, from a description.
	window_open_desc :: proc(loop: ^Loop, desc: [^]Window_Desc) -> Window ---
	// Closes a window.
	window_close :: proc(loop: ^Loop, window: Window) ---
	// Asks for one TD_EV_FRAME, when it's time to draw.
	frame_request :: proc(loop: ^Loop, window: Window) ---
	// A surface for this frame; false before the first configure or while every buffer is on screen.
	cpu_surface_acquire :: proc(loop: ^Loop, window: Window, out: [^]CPU_Surface) -> bool ---
	// Fills a surface with one color, 0x00RRGGBB.
	fill :: proc(surface: [^]CPU_Surface, xrgb: u32) ---
	// Shows a drawn surface. TD_ERR_STALE_CONFIG if drawn for an older configuration.
	present :: proc(loop: ^Loop, window: Window, surface: [^]CPU_Surface, config_seq: u64) -> Status ---
	// Decodes a WAV file; {0, 0} on failure.
	sound_load :: proc(path: cstring) -> Sound ---
	// Frees a sound once no voice plays it.
	sound_free :: proc(sound: Sound) ---
	// Plays a sound on the shared mixer; returns a voice, or 0 if it couldn't.
	mixer_play :: proc(sound: Sound, gain: f32) -> u32 ---
	// Stops a voice.
	mixer_stop :: proc(voice: u32) ---
}

// MARK: Layouts (as abigen computed them)

#assert(size_of(Window) == 8)
#assert(offset_of(Window, index) == 0)
#assert(offset_of(Window, generation) == 4)
#assert(size_of(Sound) == 8)
#assert(offset_of(Sound, index) == 0)
#assert(offset_of(Sound, generation) == 4)
#assert(size_of(Configure_Event) == 32)
#assert(offset_of(Configure_Event, width) == 0)
#assert(offset_of(Configure_Event, height) == 4)
#assert(offset_of(Configure_Event, pixel_width) == 8)
#assert(offset_of(Configure_Event, pixel_height) == 12)
#assert(offset_of(Configure_Event, scale) == 16)
#assert(offset_of(Configure_Event, flags) == 20)
#assert(offset_of(Configure_Event, config_seq) == 24)
#assert(size_of(Frame_Event) == 40)
#assert(offset_of(Frame_Event, frame_seq) == 0)
#assert(offset_of(Frame_Event, target) == 8)
#assert(offset_of(Frame_Event, presented_at) == 16)
#assert(offset_of(Frame_Event, refresh) == 24)
#assert(offset_of(Frame_Event, flags) == 32)
#assert(size_of(Key_Event) == 8)
#assert(offset_of(Key_Event, usage) == 0)
#assert(offset_of(Key_Event, modifiers) == 2)
#assert(offset_of(Key_Event, is_repeat) == 3)
#assert(offset_of(Key_Event, scancode) == 4)
#assert(size_of(Pointer_Event) == 24)
#assert(offset_of(Pointer_Event, x) == 0)
#assert(offset_of(Pointer_Event, y) == 8)
#assert(offset_of(Pointer_Event, action) == 16)
#assert(offset_of(Pointer_Event, modifiers) == 17)
#assert(offset_of(Pointer_Event, button) == 20)
#assert(size_of(Wheel_Event) == 40)
#assert(offset_of(Wheel_Event, dx) == 0)
#assert(offset_of(Wheel_Event, dy) == 8)
#assert(offset_of(Wheel_Event, steps_x) == 16)
#assert(offset_of(Wheel_Event, steps_y) == 24)
#assert(offset_of(Wheel_Event, modifiers) == 32)
#assert(size_of(Timer_Event) == 16)
#assert(offset_of(Timer_Event, timer) == 0)
#assert(offset_of(Timer_Event, missed) == 8)
#assert(size_of(Message_Event) == 16)
#assert(offset_of(Message_Event, a) == 0)
#assert(offset_of(Message_Event, b) == 8)
#assert(size_of(Event_Payload) == 48)
#assert(size_of(Event) == 80)
#assert(offset_of(Event, kind) == 0)
#assert(offset_of(Event, flags) == 2)
#assert(offset_of(Event, window) == 4)
#assert(offset_of(Event, time) == 16)
#assert(offset_of(Event, seq) == 24)
#assert(offset_of(Event, payload) == 32)
#assert(size_of(Events) == 16)
#assert(offset_of(Events, items) == 0)
#assert(offset_of(Events, count) == 8)
#assert(size_of(Window_Desc) == 24)
#assert(offset_of(Window_Desc, size) == 0)
#assert(offset_of(Window_Desc, flags) == 4)
#assert(offset_of(Window_Desc, title) == 8)
#assert(offset_of(Window_Desc, width) == 16)
#assert(offset_of(Window_Desc, height) == 20)
#assert(size_of(CPU_Surface) == 40)
#assert(offset_of(CPU_Surface, pixels) == 0)
#assert(offset_of(CPU_Surface, width) == 8)
#assert(offset_of(CPU_Surface, height) == 12)
#assert(offset_of(CPU_Surface, stride) == 16)
#assert(offset_of(CPU_Surface, age) == 20)
#assert(offset_of(CPU_Surface, window) == 24)
#assert(offset_of(CPU_Surface, buffer) == 32)
#assert(offset_of(CPU_Surface, reserved) == 36)
