// SPDX-License-Identifier: BSD-3-Clause
// Generated by abigen from lib/capi/gen/Todhchai.swift; don't edit.
//
// libtodhchai's C ABI (docs/sdk.md §12).

#ifndef TODHCHAI_TODHCHAI_H
#define TODHCHAI_TODHCHAI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// MARK: Status and errors

// 0 is success; errors are negative. The values are td_kernel.h's where they overlap.
typedef int32_t td_status;
// td_status values.
#define TD_OK 0
#define TD_ERR_NOT_SUPPORTED (-2) /* The system lacks something this needs (td_last_error names it). */
#define TD_ERR_INVALID_ARGS (-10) /* A NULL, a size too small for the struct, or a value out of range. */
#define TD_ERR_BAD_HANDLE (-11) /* The handle is stale or was never valid. */
#define TD_ERR_STALE_CONFIG (-40) /* Drawn for an older configuration: draw again for the newest (sdk.md §2). */
#define TD_ERR_IO (-41) /* A system call failed (td_last_error has errno's text). */
#define TD_ERR_BAD_FORMAT (-42) /* A file isn't in a format this reads. */
// Why this thread's last call failed, or "". Valid until this thread's next call that fails.
const char *td_last_error(void);

// MARK: Time

#define TD_FOREVER (0xffffffffffffffff) /* A deadline that never comes. */
// The monotonic clock, in nanoseconds.
uint64_t td_now(void);

// MARK: Handles

// A window. {0, 0} is none.
typedef struct td_window {
  uint32_t index;
  uint32_t generation;
} td_window;
// A decoded sound. {0, 0} is none.
typedef struct td_sound {
  uint32_t index;
  uint32_t generation;
} td_sound;

// MARK: Events

// td_event.kind.
#define TD_EV_TIMER 1 /* A timer's deadline came: `timer`. */
#define TD_EV_WATCH 2 /* Reserved: watched handles join the C ABI later. */
#define TD_EV_MESSAGE 3 /* A message posted to the loop: `message`. */
#define TD_EV_WAKE 4 /* The loop was woken (td_loop_wake). */
#define TD_EV_QUIT 5 /* The process was asked to stop (SIGINT, SIGTERM). */
#define TD_EV_CONFIGURE 6 /* A window's size, scale or state changed: `configure`. */
#define TD_EV_CLOSE 7 /* The user asked to close a window. */
#define TD_EV_FRAME 8 /* Time to draw a window's next frame: `frame`. */
#define TD_EV_KEY_DOWN 9 /* A key went down, or repeats: `key`. */
#define TD_EV_KEY_UP 10 /* A key came up: `key`. */
#define TD_EV_POINTER 11 /* The pointer entered, left, moved, or a button changed: `pointer`. */
#define TD_EV_WHEEL 12 /* A wheel or touchpad scrolled: `wheel`. */
// td_configure_event.flags.
#define TD_CONFIGURE_FOCUSED 1u /* The window has keyboard focus. */
#define TD_CONFIGURE_RESIZING 2u /* An interactive resize is under way. */
// TD_EV_CONFIGURE: draw for `config_seq`.
typedef struct td_configure_event {
  int32_t width; /* Logical size. */
  int32_t height;
  int32_t pixel_width; /* The size to draw at. */
  int32_t pixel_height;
  uint32_t scale; /* Scale × 120 (120 is 1×). */
  uint32_t flags; /* TD_CONFIGURE_*. */
  uint64_t config_seq; /* Pass to td_present. */
} td_configure_event;
// td_frame_event.flags.
#define TD_FRAME_ESTIMATED 1u /* The target time is estimated, not from the display. */
// TD_EV_FRAME.
typedef struct td_frame_event {
  uint64_t frame_seq;
  uint64_t target; /* When this frame is expected on the glass (td_now's clock). */
  uint64_t presented_at; /* When the previous frame reached the glass; 0 if unknown. */
  uint64_t refresh; /* The display's refresh interval in ns; 0 if unknown. */
  uint32_t flags; /* TD_FRAME_*. */
} td_frame_event;
// Modifier bits.
#define TD_MOD_SHIFT 1
#define TD_MOD_CONTROL 2
#define TD_MOD_ALT 4
#define TD_MOD_SUPER 8
#define TD_MOD_CAPS_LOCK 16
#define TD_MOD_NUM_LOCK 32
// TD_EV_KEY_DOWN, TD_EV_KEY_UP.
typedef struct td_key_event {
  uint16_t usage; /* The physical key: a HID keyboard usage, TD_KEY_*. */
  uint8_t modifiers; /* TD_MOD_*. */
  bool is_repeat; /* Held down and repeating. */
  uint32_t scancode; /* The platform's code, for remapping UIs. */
} td_key_event;
// td_pointer_event.action.
#define TD_POINTER_ENTER 1
#define TD_POINTER_LEAVE 2
#define TD_POINTER_MOTION 3
#define TD_POINTER_DOWN 4
#define TD_POINTER_UP 5
// td_pointer_event.button; other buttons are the platform's code plus 256.
#define TD_BUTTON_LEFT 1u
#define TD_BUTTON_RIGHT 2u
#define TD_BUTTON_MIDDLE 3u
#define TD_BUTTON_BACK 4u
#define TD_BUTTON_FORWARD 5u
// TD_EV_POINTER.
typedef struct td_pointer_event {
  double x; /* Position in logical units. */
  double y;
  uint8_t action; /* TD_POINTER_*. */
  uint8_t modifiers; /* TD_MOD_*. */
  uint32_t button; /* For DOWN and UP: TD_BUTTON_*. */
} td_pointer_event;
// TD_EV_WHEEL.
typedef struct td_wheel_event {
  double dx; /* Scroll distance in logical units. */
  double dy;
  double steps_x; /* Wheel detents, where the device has them. */
  double steps_y;
  uint8_t modifiers; /* TD_MOD_*. */
} td_wheel_event;
// TD_EV_TIMER.
typedef struct td_timer_event {
  uint64_t timer; /* From td_timer_set. */
  uint64_t missed; /* Repeats skipped because the loop was late. */
} td_timer_event;
// TD_EV_MESSAGE.
typedef struct td_message_event {
  uint64_t a;
  uint64_t b;
} td_message_event;
// One event: 80 bytes (sdk.md §2).
typedef struct td_event {
  uint16_t kind; /* TD_EV_*. */
  uint16_t flags; /* Reserved: 0. */
  td_window window; /* The window it's for, or {0, 0}. */
  uint64_t time; /* When it was taken (td_now's clock). */
  uint64_t seq; /* Its place in the loop's sequence, from 1. */
  union { /* The kind's data. */
    td_configure_event configure;
    td_frame_event frame;
    td_key_event key;
    td_pointer_event pointer;
    td_wheel_event wheel;
    td_timer_event timer;
    td_message_event message;
    uint8_t bytes[48];
  };
} td_event;
// The events one wait returned: valid until the next wait on the same loop.
typedef struct td_events {
  const td_event *items;
  size_t count;
} td_events;

// MARK: The loop

// A run loop: one per thread that waits.
typedef struct td_loop td_loop;
// A loop for this thread, or NULL (td_last_error says why).
td_loop *td_loop_create(void);
// Closes its windows and frees it.
void td_loop_destroy(td_loop *loop);
// Waits until there are events or `deadline`; frames come last in a batch.
td_events td_loop_wait(td_loop *loop, uint64_t deadline, uint64_t leeway);
// The events ready now, without waiting.
td_events td_loop_poll(td_loop *loop);
// Wakes the loop (TD_EV_WAKE), from any thread.
void td_loop_wake(td_loop *loop);
// Posts TD_EV_MESSAGE, from any thread.
void td_loop_post(td_loop *loop, uint64_t a, uint64_t b);
// A timer; TD_EV_TIMER carries the returned id.
uint64_t td_timer_set(td_loop *loop, uint64_t deadline, uint64_t leeway, uint64_t repeat);
// Cancels a timer.
void td_timer_cancel(td_loop *loop, uint64_t timer);

// MARK: Windows

// A window to open (an input struct: set `size`).
typedef struct td_window_desc {
  uint32_t size; /* sizeof(td_window_desc). */
  uint32_t flags; /* Reserved: 0. */
  const char *title;
  int32_t width; /* Logical size. */
  int32_t height;
} td_window_desc;
// Opens a window; {0, 0} on failure. TD_EV_CONFIGURE follows.
td_window td_window_open(td_loop *loop, const char *title, int32_t width, int32_t height);
// td_window_open, from a description.
td_window td_window_open_desc(td_loop *loop, const td_window_desc *desc);
// Closes a window.
void td_window_close(td_loop *loop, td_window window);
// Asks for one TD_EV_FRAME, when it's time to draw.
void td_frame_request(td_loop *loop, td_window window);
// Pixels to draw into, XRGB8888 (an output struct).
typedef struct td_cpu_surface {
  void *pixels;
  int32_t width;
  int32_t height;
  uint32_t stride; /* Bytes a row. */
  uint32_t age; /* Frames since this buffer was last shown (0: never), for partial redraw. */
  td_window window;
  uint32_t buffer; /* The SDK's own: leave it. */
  uint32_t reserved;
} td_cpu_surface;
// A surface for this frame; false before the first configure or while every buffer is on screen.
bool td_cpu_surface_acquire(td_loop *loop, td_window window, td_cpu_surface *out);
// Fills a surface with one color, 0x00RRGGBB.
void td_fill(const td_cpu_surface *surface, uint32_t xrgb);
// Shows a drawn surface. TD_ERR_STALE_CONFIG if drawn for an older configuration.
td_status td_present(td_loop *loop, td_window window, const td_cpu_surface *surface, uint64_t config_seq);

// MARK: Sound

// Decodes a WAV file; {0, 0} on failure.
td_sound td_sound_load(const char *path);
// Frees a sound once no voice plays it.
void td_sound_free(td_sound sound);
// Plays a sound on the shared mixer; returns a voice, or 0 if it couldn't.
uint32_t td_mixer_play(td_sound sound, float gain);
// Stops a voice.
void td_mixer_stop(uint32_t voice);

// MARK: Keys: HID keyboard usages (lib/sdk/KeyUsage.swift)

#define TD_KEY_A 4
#define TD_KEY_B 5
#define TD_KEY_C 6
#define TD_KEY_D 7
#define TD_KEY_E 8
#define TD_KEY_F 9
#define TD_KEY_G 10
#define TD_KEY_H 11
#define TD_KEY_I 12
#define TD_KEY_J 13
#define TD_KEY_K 14
#define TD_KEY_L 15
#define TD_KEY_M 16
#define TD_KEY_N 17
#define TD_KEY_O 18
#define TD_KEY_P 19
#define TD_KEY_Q 20
#define TD_KEY_R 21
#define TD_KEY_S 22
#define TD_KEY_T 23
#define TD_KEY_U 24
#define TD_KEY_V 25
#define TD_KEY_W 26
#define TD_KEY_X 27
#define TD_KEY_Y 28
#define TD_KEY_Z 29
#define TD_KEY_DIGIT1 30
#define TD_KEY_DIGIT2 31
#define TD_KEY_DIGIT3 32
#define TD_KEY_DIGIT4 33
#define TD_KEY_DIGIT5 34
#define TD_KEY_DIGIT6 35
#define TD_KEY_DIGIT7 36
#define TD_KEY_DIGIT8 37
#define TD_KEY_DIGIT9 38
#define TD_KEY_DIGIT0 39
#define TD_KEY_ENTER 40
#define TD_KEY_ESCAPE 41
#define TD_KEY_BACKSPACE 42
#define TD_KEY_TAB 43
#define TD_KEY_SPACE 44
#define TD_KEY_MINUS 45
#define TD_KEY_EQUAL 46
#define TD_KEY_LEFT_BRACKET 47
#define TD_KEY_RIGHT_BRACKET 48
#define TD_KEY_BACKSLASH 49
#define TD_KEY_NON_US_HASH 50
#define TD_KEY_SEMICOLON 51
#define TD_KEY_APOSTROPHE 52
#define TD_KEY_GRAVE 53
#define TD_KEY_COMMA 54
#define TD_KEY_PERIOD 55
#define TD_KEY_SLASH 56
#define TD_KEY_CAPS_LOCK 57
#define TD_KEY_F1 58
#define TD_KEY_F2 59
#define TD_KEY_F3 60
#define TD_KEY_F4 61
#define TD_KEY_F5 62
#define TD_KEY_F6 63
#define TD_KEY_F7 64
#define TD_KEY_F8 65
#define TD_KEY_F9 66
#define TD_KEY_F10 67
#define TD_KEY_F11 68
#define TD_KEY_F12 69
#define TD_KEY_PRINT_SCREEN 70
#define TD_KEY_SCROLL_LOCK 71
#define TD_KEY_PAUSE 72
#define TD_KEY_INSERT 73
#define TD_KEY_HOME 74
#define TD_KEY_PAGE_UP 75
#define TD_KEY_DELETE 76
#define TD_KEY_END 77
#define TD_KEY_PAGE_DOWN 78
#define TD_KEY_RIGHT 79
#define TD_KEY_LEFT 80
#define TD_KEY_DOWN 81
#define TD_KEY_UP 82
#define TD_KEY_NUM_LOCK 83
#define TD_KEY_KEYPAD_SLASH 84
#define TD_KEY_KEYPAD_ASTERISK 85
#define TD_KEY_KEYPAD_MINUS 86
#define TD_KEY_KEYPAD_PLUS 87
#define TD_KEY_KEYPAD_ENTER 88
#define TD_KEY_KEYPAD1 89
#define TD_KEY_KEYPAD2 90
#define TD_KEY_KEYPAD3 91
#define TD_KEY_KEYPAD4 92
#define TD_KEY_KEYPAD5 93
#define TD_KEY_KEYPAD6 94
#define TD_KEY_KEYPAD7 95
#define TD_KEY_KEYPAD8 96
#define TD_KEY_KEYPAD9 97
#define TD_KEY_KEYPAD0 98
#define TD_KEY_KEYPAD_PERIOD 99
#define TD_KEY_NON_US_BACKSLASH 100
#define TD_KEY_APPLICATION 101
#define TD_KEY_POWER 102
#define TD_KEY_KEYPAD_EQUAL 103
#define TD_KEY_F13 104
#define TD_KEY_F14 105
#define TD_KEY_F15 106
#define TD_KEY_F16 107
#define TD_KEY_F17 108
#define TD_KEY_F18 109
#define TD_KEY_F19 110
#define TD_KEY_F20 111
#define TD_KEY_F21 112
#define TD_KEY_F22 113
#define TD_KEY_F23 114
#define TD_KEY_F24 115
#define TD_KEY_MUTE 127
#define TD_KEY_VOLUME_UP 128
#define TD_KEY_VOLUME_DOWN 129
#define TD_KEY_KEYPAD_COMMA 133
#define TD_KEY_LEFT_CONTROL 224
#define TD_KEY_LEFT_SHIFT 225
#define TD_KEY_LEFT_ALT 226
#define TD_KEY_LEFT_SUPER 227
#define TD_KEY_RIGHT_CONTROL 228
#define TD_KEY_RIGHT_SHIFT 229
#define TD_KEY_RIGHT_ALT 230
#define TD_KEY_RIGHT_SUPER 231

// MARK: Layouts (as abigen computed them)

#ifdef __cplusplus
#define TD_ABI_ASSERT(e, m) static_assert(e, m)
#else
#define TD_ABI_ASSERT(e, m) _Static_assert(e, m)
#endif
TD_ABI_ASSERT(sizeof(td_window) == 8, "td_window");
TD_ABI_ASSERT(offsetof(td_window, index) == 0, "td_window.index");
TD_ABI_ASSERT(offsetof(td_window, generation) == 4, "td_window.generation");
TD_ABI_ASSERT(sizeof(td_sound) == 8, "td_sound");
TD_ABI_ASSERT(offsetof(td_sound, index) == 0, "td_sound.index");
TD_ABI_ASSERT(offsetof(td_sound, generation) == 4, "td_sound.generation");
TD_ABI_ASSERT(sizeof(td_configure_event) == 32, "td_configure_event");
TD_ABI_ASSERT(offsetof(td_configure_event, width) == 0, "td_configure_event.width");
TD_ABI_ASSERT(offsetof(td_configure_event, height) == 4, "td_configure_event.height");
TD_ABI_ASSERT(offsetof(td_configure_event, pixel_width) == 8, "td_configure_event.pixel_width");
TD_ABI_ASSERT(offsetof(td_configure_event, pixel_height) == 12, "td_configure_event.pixel_height");
TD_ABI_ASSERT(offsetof(td_configure_event, scale) == 16, "td_configure_event.scale");
TD_ABI_ASSERT(offsetof(td_configure_event, flags) == 20, "td_configure_event.flags");
TD_ABI_ASSERT(offsetof(td_configure_event, config_seq) == 24, "td_configure_event.config_seq");
TD_ABI_ASSERT(sizeof(td_frame_event) == 40, "td_frame_event");
TD_ABI_ASSERT(offsetof(td_frame_event, frame_seq) == 0, "td_frame_event.frame_seq");
TD_ABI_ASSERT(offsetof(td_frame_event, target) == 8, "td_frame_event.target");
TD_ABI_ASSERT(offsetof(td_frame_event, presented_at) == 16, "td_frame_event.presented_at");
TD_ABI_ASSERT(offsetof(td_frame_event, refresh) == 24, "td_frame_event.refresh");
TD_ABI_ASSERT(offsetof(td_frame_event, flags) == 32, "td_frame_event.flags");
TD_ABI_ASSERT(sizeof(td_key_event) == 8, "td_key_event");
TD_ABI_ASSERT(offsetof(td_key_event, usage) == 0, "td_key_event.usage");
TD_ABI_ASSERT(offsetof(td_key_event, modifiers) == 2, "td_key_event.modifiers");
TD_ABI_ASSERT(offsetof(td_key_event, is_repeat) == 3, "td_key_event.is_repeat");
TD_ABI_ASSERT(offsetof(td_key_event, scancode) == 4, "td_key_event.scancode");
TD_ABI_ASSERT(sizeof(td_pointer_event) == 24, "td_pointer_event");
TD_ABI_ASSERT(offsetof(td_pointer_event, x) == 0, "td_pointer_event.x");
TD_ABI_ASSERT(offsetof(td_pointer_event, y) == 8, "td_pointer_event.y");
TD_ABI_ASSERT(offsetof(td_pointer_event, action) == 16, "td_pointer_event.action");
TD_ABI_ASSERT(offsetof(td_pointer_event, modifiers) == 17, "td_pointer_event.modifiers");
TD_ABI_ASSERT(offsetof(td_pointer_event, button) == 20, "td_pointer_event.button");
TD_ABI_ASSERT(sizeof(td_wheel_event) == 40, "td_wheel_event");
TD_ABI_ASSERT(offsetof(td_wheel_event, dx) == 0, "td_wheel_event.dx");
TD_ABI_ASSERT(offsetof(td_wheel_event, dy) == 8, "td_wheel_event.dy");
TD_ABI_ASSERT(offsetof(td_wheel_event, steps_x) == 16, "td_wheel_event.steps_x");
TD_ABI_ASSERT(offsetof(td_wheel_event, steps_y) == 24, "td_wheel_event.steps_y");
TD_ABI_ASSERT(offsetof(td_wheel_event, modifiers) == 32, "td_wheel_event.modifiers");
TD_ABI_ASSERT(sizeof(td_timer_event) == 16, "td_timer_event");
TD_ABI_ASSERT(offsetof(td_timer_event, timer) == 0, "td_timer_event.timer");
TD_ABI_ASSERT(offsetof(td_timer_event, missed) == 8, "td_timer_event.missed");
TD_ABI_ASSERT(sizeof(td_message_event) == 16, "td_message_event");
TD_ABI_ASSERT(offsetof(td_message_event, a) == 0, "td_message_event.a");
TD_ABI_ASSERT(offsetof(td_message_event, b) == 8, "td_message_event.b");
TD_ABI_ASSERT(sizeof(td_event) == 80, "td_event");
TD_ABI_ASSERT(offsetof(td_event, kind) == 0, "td_event.kind");
TD_ABI_ASSERT(offsetof(td_event, flags) == 2, "td_event.flags");
TD_ABI_ASSERT(offsetof(td_event, window) == 4, "td_event.window");
TD_ABI_ASSERT(offsetof(td_event, time) == 16, "td_event.time");
TD_ABI_ASSERT(offsetof(td_event, seq) == 24, "td_event.seq");
TD_ABI_ASSERT(offsetof(td_event, configure) == 32, "td_event.configure");
TD_ABI_ASSERT(offsetof(td_event, frame) == 32, "td_event.frame");
TD_ABI_ASSERT(offsetof(td_event, key) == 32, "td_event.key");
TD_ABI_ASSERT(offsetof(td_event, pointer) == 32, "td_event.pointer");
TD_ABI_ASSERT(offsetof(td_event, wheel) == 32, "td_event.wheel");
TD_ABI_ASSERT(offsetof(td_event, timer) == 32, "td_event.timer");
TD_ABI_ASSERT(offsetof(td_event, message) == 32, "td_event.message");
TD_ABI_ASSERT(offsetof(td_event, bytes) == 32, "td_event.bytes");
TD_ABI_ASSERT(sizeof(td_events) == 16, "td_events");
TD_ABI_ASSERT(offsetof(td_events, items) == 0, "td_events.items");
TD_ABI_ASSERT(offsetof(td_events, count) == 8, "td_events.count");
TD_ABI_ASSERT(sizeof(td_window_desc) == 24, "td_window_desc");
TD_ABI_ASSERT(offsetof(td_window_desc, size) == 0, "td_window_desc.size");
TD_ABI_ASSERT(offsetof(td_window_desc, flags) == 4, "td_window_desc.flags");
TD_ABI_ASSERT(offsetof(td_window_desc, title) == 8, "td_window_desc.title");
TD_ABI_ASSERT(offsetof(td_window_desc, width) == 16, "td_window_desc.width");
TD_ABI_ASSERT(offsetof(td_window_desc, height) == 20, "td_window_desc.height");
TD_ABI_ASSERT(sizeof(td_cpu_surface) == 40, "td_cpu_surface");
TD_ABI_ASSERT(offsetof(td_cpu_surface, pixels) == 0, "td_cpu_surface.pixels");
TD_ABI_ASSERT(offsetof(td_cpu_surface, width) == 8, "td_cpu_surface.width");
TD_ABI_ASSERT(offsetof(td_cpu_surface, height) == 12, "td_cpu_surface.height");
TD_ABI_ASSERT(offsetof(td_cpu_surface, stride) == 16, "td_cpu_surface.stride");
TD_ABI_ASSERT(offsetof(td_cpu_surface, age) == 20, "td_cpu_surface.age");
TD_ABI_ASSERT(offsetof(td_cpu_surface, window) == 24, "td_cpu_surface.window");
TD_ABI_ASSERT(offsetof(td_cpu_surface, buffer) == 32, "td_cpu_surface.buffer");
TD_ABI_ASSERT(offsetof(td_cpu_surface, reserved) == 36, "td_cpu_surface.reserved");
#undef TD_ABI_ASSERT

#ifdef __cplusplus
}
#endif

#endif
