// SPDX-License-Identifier: BSD-3-Clause

// ucdgen's work: the Unicode Character Database files in data/unicode
// become the sorted tables TDUnicode searches (lib/unicode/generated). The
// rules are UAX #15's (Unicode Normalization Forms) and UCD's
// CaseFolding.txt header.

public struct UCD {
  public var version: String
  /// Canonical combining class of each code point that has a nonzero one.
  public var combiningClass: [UInt32: UInt8] = [:]
  /// Each code point's canonical decomposition mapping, one level.
  public var decomposition: [UInt32: [UInt32]] = [:]
  public var exclusions: Set<UInt32> = []
  /// Full case folding (statuses C and F).
  public var folding: [UInt32: [UInt32]] = [:]

  public init(unicodeData: String, compositionExclusions: String, caseFolding: String) {
    version = "unknown"
    if let first = caseFolding.split(separator: "\n").first, let dash = first.lastIndex(of: "-") {
      version = String(first[first.index(after: dash)...].prefix { $0 != "." || true }.dropLast(4))
    }
    for line in unicodeData.split(separator: "\n") {
      let f = line.split(separator: ";", omittingEmptySubsequences: false)
      guard f.count >= 6, let cp = UInt32(f[0], radix: 16) else { continue }
      if let ccc = UInt8(f[3]), ccc != 0 { combiningClass[cp] = ccc }
      // Compatibility mappings start with a <tag>; only canonical ones count.
      if !f[5].isEmpty, !f[5].hasPrefix("<") {
        decomposition[cp] = f[5].split(separator: " ").compactMap { UInt32($0, radix: 16) }
      }
    }
    for line in compositionExclusions.split(separator: "\n") {
      let code = line.prefix { $0 != "#" }.trimmingCharacters()
      if let cp = UInt32(code, radix: 16) { exclusions.insert(cp) }
    }
    for line in caseFolding.split(separator: "\n") where !line.hasPrefix("#") {
      let f = line.split(separator: ";").map { $0.trimmingCharacters() }
      guard f.count >= 3, f[1] == "C" || f[1] == "F", let cp = UInt32(f[0], radix: 16) else { continue }
      folding[cp] = f[2].split(separator: " ").compactMap { UInt32($0, radix: 16) }
    }
  }

  /// The full canonical decomposition: mappings applied until none apply.
  public func fullDecomposition(_ cp: UInt32) -> [UInt32] {
    guard let d = decomposition[cp] else { return [cp] }
    return d.flatMap { fullDecomposition($0) }
  }

  /// Full_Composition_Exclusion (UAX #15 §5): the listed exclusions,
  /// singletons, and decompositions that don't start with a starter.
  public func isExcluded(_ cp: UInt32) -> Bool {
    guard let d = decomposition[cp] else { return false }
    return exclusions.contains(cp) || d.count == 1 || combiningClass[cp] != nil || combiningClass[d[0]] != nil
  }

  /// Primary composites: a pair to what it composes to.
  public var compositions: [(first: UInt32, second: UInt32, composite: UInt32)] {
    decomposition.compactMap { cp, d in d.count == 2 && !isExcluded(cp) ? (d[0], d[1], cp) : nil }
      .sorted { ($0.first, $0.second) < ($1.first, $1.second) }
  }

  /// The generated Swift.
  public func swift() -> String {
    var s = """
      // SPDX-License-Identifier: BSD-3-Clause
      // Generated by ucdgen from data/unicode (Unicode \(version)); don't edit.

      enum Tables {

      """
    // Combining classes, as ranges of one class: start, end, class.
    var ranges: [UInt32] = []
    for cp in combiningClass.keys.sorted() {
      let c = UInt32(combiningClass[cp]!)
      if ranges.count >= 3, ranges[ranges.count - 2] == cp - 1, ranges[ranges.count - 1] == c {
        ranges[ranges.count - 2] = cp
      } else {
        ranges += [cp, cp, c]
      }
    }
    s += table("combiningClass", "UInt32", ranges, "Nonzero canonical combining classes: (first, last, class) triples, sorted.")
    let (dk, ds, dd) = packed(decomposition.keys.sorted().map { ($0, fullDecomposition($0)) })
    s += table("decompositionKeys", "UInt32", dk, "Code points with a canonical decomposition, sorted (Hangul is computed).")
    s += table("decompositionStarts", "UInt16", ds, "Where each one's full decomposition starts in decompositionData (one more entry: the end).")
    s += table("decompositionData", "UInt32", dd, "")
    let comps = compositions
    s += table("compositionPairs", "UInt64", comps.map { UInt64($0.first) << 21 | UInt64($0.second) }, "Primary composites: (first << 21 | second), sorted.")
    s += table("compositionResults", "UInt32", comps.map(\.composite), "What each pair composes to.")
    let (fk, fs, fd) = packed(folding.keys.sorted().map { ($0, folding[$0]!) })
    s += table("foldKeys", "UInt32", fk, "Code points that case-fold (full folding: C and F), sorted.")
    s += table("foldStarts", "UInt16", fs, "Where each one's folding starts in foldData (one more entry: the end).")
    s += table("foldData", "UInt32", fd, "")
    return s + "}\n"
  }

  func packed(_ entries: [(UInt32, [UInt32])]) -> ([UInt64], [UInt64], [UInt64]) {
    var keys: [UInt64] = [], starts: [UInt64] = [], data: [UInt64] = []
    for (cp, d) in entries {
      keys.append(UInt64(cp))
      starts.append(UInt64(data.count))
      data += d.map(UInt64.init)
    }
    starts.append(UInt64(data.count))
    return (keys, starts, data)
  }

  func table<T: BinaryInteger>(_ name: String, _ type: String, _ values: [T], _ doc: String) -> String {
    var s = doc.isEmpty ? "" : "  /// \(doc)\n"
    s += "  static let \(name): [\(type)] = [\n"
    var line = "   "
    for v in values {
      let item = " 0x" + String(v, radix: 16) + ","
      if line.count + item.count > 116 {
        s += line + "\n"
        line = "   "
      }
      line += item
    }
    if line != "   " { s += line + "\n" }
    return s + "  ]\n\n"
  }
}

extension Substring {
  func trimmingCharacters() -> String {
    String(drop { $0 == " " || $0 == "\t" }.reversed().drop { $0 == " " || $0 == "\t" }.reversed())
  }
}
extension String {
  func trimmingCharacters() -> String { self[...].trimmingCharacters() }
}
