// SPDX-License-Identifier: BSD-3-Clause

// td libc-symbols: what the toolchain's Swift runtime and
// FoundationEssentials import from the platform's C and C++ runtimes, from
// the Linux build of the pinned toolchain. Our libc is written against this
// list (roadmap F track; architecture §20). Writes lib/libc/symbols.tsv:
//
//   symbol<TAB>runtime<TAB>libraries
//
// runtime is glibc (C), cxxabi (the C++ ABI), libstdc++ (the C++ standard
// library) or libgcc (compiler support: 128-bit division, unwinding).

import FoundationEssentials
import Glibc

/// The runtime libraries tier 1 uses (principle 29: the stdlib, runtime,
/// concurrency runtime and FoundationEssentials are toolchain).
let runtimeLibraries = [
  "libswiftCore", "libswiftRuntime", "libswift_Concurrency", "libswiftSynchronization",
  "libswift_StringProcessing", "libFoundationEssentials",
]

func libcSymbols() -> Bool {
  guard let swiftc = capture(["swiftly", "use", "--print-location"]) else {
    fail("can't find the toolchain (swiftly use --print-location)")
  }
  let dir = "\(swiftc)/usr/lib/swift/linux"
  var needs: [String: (runtime: String, libraries: [String])] = [:]
  for library in runtimeLibraries {
    let path = "\(dir)/\(library).so"
    guard let listing = capture(["nm", "-D", "--undefined-only", path]) else { fail("can't read \(path)") }
    for line in listing.split(separator: "\n") {
      guard let versioned = line.split(separator: " ").last, let at = versioned.firstIndex(of: "@") else { continue }
      let symbol = String(versioned[..<at])
      let version = versioned[versioned.index(after: at)...]
      let runtime = version.hasPrefix("GLIBC_") ? "glibc"
        : version.hasPrefix("CXXABI_") ? "cxxabi"
        : version.hasPrefix("GLIBCXX_") ? "libstdc++"
        : version.hasPrefix("GCC_") ? "libgcc" : nil
      guard let runtime else { continue }
      needs[symbol, default: (runtime, [])].libraries.append(library)
    }
  }
  var text = "# Generated by td libc-symbols from the Linux build of \(trimmed(capture(["swift", "--version"])?.split(separator: "\n").first ?? "")).\n"
  text += "# symbol\truntime\tlibraries\n"
  for (symbol, need) in needs.sorted(by: { ($0.value.runtime, $0.key) < ($1.value.runtime, $1.key) }) {
    text += "\(symbol)\t\(need.runtime)\t\(need.libraries.joined(separator: ","))\n"
  }
  let path = "lib/libc/symbols.tsv"
  do { try text.write(toFile: path, atomically: true, encoding: .utf8) } catch { fail("can't write \(path)") }
  let counts = Dictionary(grouping: needs.values, by: \.runtime).mapValues(\.count)
  say("wrote \(path): " + counts.sorted { $0.key < $1.key }.map { "\($0.value) \($0.key)" }.joined(separator: ", "))
  return true
}
