// SPDX-License-Identifier: BSD-3-Clause
//
// Generated by idlc from lib/node/Node.swift. Do not edit.
//
// Library todhchai.node, version 1: the client side in C.
// Strings are pointer plus length (UTF-8, not NUL-terminated); optional
// values are pointers, NULL when absent (TD_HANDLE_INVALID for handles).
// What a reply returns points into the message buffer the call was
// given, and into the arena for vectors' elements and optional values.

#ifndef NODE_IPC_IDL_H
#define NODE_IPC_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <td_wire.h>

#ifdef __cplusplus
extern "C" {
#endif

#define NODE_PROTOCOL_ID "todhchai.node.Node"
#define NODE_VERSION 1
#define NODE_WALK_ORDINAL UINT64_C(0x343cf027b316ca04)
#define NODE_STAT_ORDINAL UINT64_C(0x7e3b0e09a1cf2ddb)
#define NODE_READDIR_ORDINAL UINT64_C(0x6460f99c249915e8)
#define NODE_READ_ORDINAL UINT64_C(0xeff770ff36c3359)
#define NODE_WRITE_ORDINAL UINT64_C(0x2ae487e0190bcba0)
#define NODE_WATCH_ORDINAL UINT64_C(0x97dc774d9295874)
#define NODE_CHANGED_ORDINAL UINT64_C(0x2afaaea991fb27e7)
#define NODE_CREATE_ORDINAL UINT64_C(0x4ffd58d55ba2f869)
#define NODE_REMOVE_ORDINAL UINT64_C(0x585c72da4f9cf049)

// NodeError: codes in error replies (td_wire_call returns TD_ERR_REMOTE).
#define NODE_ERROR_NOT_FOUND 1
#define NODE_ERROR_NOT_DIRECTORY 2
#define NODE_ERROR_IS_DIRECTORY 3
#define NODE_ERROR_EXISTS 4
#define NODE_ERROR_DENIED 5
#define NODE_ERROR_BAD_NAME 6
#define NODE_ERROR_TOO_MANY_NAMES 7
#define NODE_ERROR_NOT_EMPTY 8
#define NODE_ERROR_UNSUPPORTED 9
#define NODE_ERROR_INVALID 10
#define NODE_ERROR_IO 11

// enum NodeKind (UInt8): receivers reject other values.
typedef uint8_t node_ipc_node_kind_t;
#define NODE_IPC_NODE_KIND_FILE ((node_ipc_node_kind_t)1)
#define NODE_IPC_NODE_KIND_DIRECTORY ((node_ipc_node_kind_t)2)
#define NODE_IPC_NODE_KIND_SERVICE ((node_ipc_node_kind_t)3)
static inline int node_ipc_node_kind_known(uint64_t v) { return v == UINT64_C(1) || v == UINT64_C(2) || v == UINT64_C(3); }

// enum ChangeKind (UInt8): receivers reject other values.
typedef uint8_t node_ipc_change_kind_t;
#define NODE_IPC_CHANGE_KIND_CREATED ((node_ipc_change_kind_t)1)
#define NODE_IPC_CHANGE_KIND_REMOVED ((node_ipc_change_kind_t)2)
#define NODE_IPC_CHANGE_KIND_MODIFIED ((node_ipc_change_kind_t)3)
#define NODE_IPC_CHANGE_KIND_OVERFLOW ((node_ipc_change_kind_t)4)
static inline int node_ipc_change_kind_known(uint64_t v) { return v == UINT64_C(1) || v == UINT64_C(2) || v == UINT64_C(3) || v == UINT64_C(4); }

typedef struct node_ipc_qid node_ipc_qid_t;
typedef struct node_ipc_attribute node_ipc_attribute_t;
typedef struct node_ipc_stat node_ipc_stat_t;
typedef struct node_ipc_dir_batch node_ipc_dir_batch_t;
typedef struct node_ipc_walked node_ipc_walked_t;
typedef struct node_ipc_change node_ipc_change_t;

typedef struct node_ipc_vec_attribute {
  const node_ipc_attribute_t *items;
  uint32_t count;
} node_ipc_vec_attribute_t;

typedef struct node_ipc_vec_stat {
  const node_ipc_stat_t *items;
  uint32_t count;
} node_ipc_vec_stat_t;

typedef struct node_ipc_vec_qid {
  const node_ipc_qid_t *items;
  uint32_t count;
} node_ipc_vec_qid_t;

typedef struct node_ipc_vec_str {
  const td_wire_str_t *items;
  uint32_t count;
} node_ipc_vec_str_t;

struct node_ipc_qid {
  uint64_t path;
  uint32_t version;
  node_ipc_node_kind_t kind;
};

struct node_ipc_attribute {
  td_wire_str_t name;
  uint8_t kind;
  td_wire_bytes_t value;
};

struct node_ipc_stat {
  node_ipc_qid_t qid;
  td_wire_str_t name;
  uint64_t size;
  int64_t modified;
  node_ipc_vec_attribute_t attributes;
};

struct node_ipc_dir_batch {
  node_ipc_vec_stat_t entries;
  uint64_t next;
  bool done;
};

struct node_ipc_walked {
  node_ipc_vec_qid_t qids;
  td_handle_t node;
};

struct node_ipc_change {
  uint64_t seq;
  node_ipc_change_kind_t kind;
  td_wire_str_t name;
};

static inline td_status_t node_ipc_qid_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_qid_t *in);
static inline td_status_t node_ipc_qid_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_qid_t *out);
static inline td_status_t node_ipc_attribute_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_attribute_t *in);
static inline td_status_t node_ipc_attribute_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_attribute_t *out);
static inline td_status_t node_ipc_stat_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_stat_t *in);
static inline td_status_t node_ipc_stat_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_stat_t *out);
static inline td_status_t node_ipc_dir_batch_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_dir_batch_t *in);
static inline td_status_t node_ipc_dir_batch_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_dir_batch_t *out);
static inline td_status_t node_ipc_walked_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_walked_t *in);
static inline td_status_t node_ipc_walked_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_walked_t *out);
static inline td_status_t node_ipc_change_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_change_t *in);
static inline td_status_t node_ipc_change_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_change_t *out);

static inline td_status_t node_ipc_qid_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_qid_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  td_wire_store(m, o + 0, (uint64_t)(in->path), 8);
  td_wire_store(m, o + 8, (uint64_t)(in->version), 4);
  td_wire_store(m, o + 12, (uint64_t)(in->kind), 1);
  return TD_OK;
}

static inline td_status_t node_ipc_qid_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_qid_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 13, 3) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 0, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->path = (uint64_t)(uint64_t)v;
  if (td_wire_load(r, o + 8, 4, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->version = (uint32_t)(uint32_t)v;
  if (td_wire_load(r, o + 12, 1, &v) != TD_OK || !node_ipc_node_kind_known(v)) return TD_ERR_PROTOCOL;
  out->kind = (node_ipc_node_kind_t)(uint8_t)v;
  return TD_OK;
}

static inline td_status_t node_ipc_attribute_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_attribute_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = td_wire_store_bytes(m, o + 0, (in->name).data, (in->name).len)) != TD_OK) return s;
  td_wire_store(m, o + 16, (uint64_t)(in->kind), 1);
  if ((s = td_wire_store_bytes(m, o + 24, (in->value).data, (in->value).len)) != TD_OK) return s;
  return TD_OK;
}

static inline td_status_t node_ipc_attribute_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_attribute_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 17, 7) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_string(r, o + 0, &(out->name).data, &(out->name).len) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 16, 1, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->kind = (uint8_t)(uint8_t)v;
  if (td_wire_load_bytes(r, o + 24, &(out->value).data, &(out->value).len) != TD_OK) return TD_ERR_PROTOCOL;
  return TD_OK;
}

static inline td_status_t node_ipc_stat_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_stat_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  if ((s = node_ipc_qid_encode(m, o + 0, &(in->qid))) != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, o + 16, (in->name).data, (in->name).len)) != TD_OK) return s;
  td_wire_store(m, o + 32, (uint64_t)(in->size), 8);
  td_wire_store(m, o + 40, (uint64_t)(in->modified), 8);
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, o + 48, (in->attributes).count, 40, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (in->attributes).count; i0++) {
  if ((s = node_ipc_attribute_encode(m, b0 + i0 * 40, &((in->attributes).items[i0]))) != TD_OK) return s;
  }
  }
  return TD_OK;
}

static inline td_status_t node_ipc_stat_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_stat_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if ((s = node_ipc_qid_decode(r, o + 0, a, &(out->qid))) != TD_OK) return s;
  if (td_wire_load_string(r, o + 16, &(out->name).data, &(out->name).len) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 32, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->size = (uint64_t)(uint64_t)v;
  if (td_wire_load(r, o + 40, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->modified = (int64_t)(uint64_t)v;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, o + 48, 40, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  node_ipc_attribute_t *e0 = (node_ipc_attribute_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(node_ipc_attribute_t), (uint32_t)_Alignof(node_ipc_attribute_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if ((s = node_ipc_attribute_decode(r, b0 + i0 * 40, a, &(e0[i0]))) != TD_OK) return s;
  }
  (out->attributes).items = (const node_ipc_attribute_t *)e0;
  (out->attributes).count = n0;
  }
  return TD_OK;
}

static inline td_status_t node_ipc_dir_batch_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_dir_batch_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, o + 0, (in->entries).count, 64, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (in->entries).count; i0++) {
  if ((s = node_ipc_stat_encode(m, b0 + i0 * 64, &((in->entries).items[i0]))) != TD_OK) return s;
  }
  }
  td_wire_store(m, o + 16, (uint64_t)(in->next), 8);
  td_wire_store(m, o + 24, (in->done) ? 1 : 0, 1);
  return TD_OK;
}

static inline td_status_t node_ipc_dir_batch_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_dir_batch_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 25, 7) != TD_OK) return TD_ERR_PROTOCOL;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, o + 0, 64, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  node_ipc_stat_t *e0 = (node_ipc_stat_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(node_ipc_stat_t), (uint32_t)_Alignof(node_ipc_stat_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if ((s = node_ipc_stat_decode(r, b0 + i0 * 64, a, &(e0[i0]))) != TD_OK) return s;
  }
  (out->entries).items = (const node_ipc_stat_t *)e0;
  (out->entries).count = n0;
  }
  if (td_wire_load(r, o + 16, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->next = (uint64_t)(uint64_t)v;
  { uint8_t b; if (td_wire_load_bool(r, o + 24, &b) != TD_OK) return TD_ERR_PROTOCOL; out->done = b; }
  return TD_OK;
}

static inline td_status_t node_ipc_walked_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_walked_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, o + 0, (in->qids).count, 16, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (in->qids).count; i0++) {
  if ((s = node_ipc_qid_encode(m, b0 + i0 * 16, &((in->qids).items[i0]))) != TD_OK) return s;
  }
  }
  if ((s = td_wire_store_handle(m, o + 16, in->node)) != TD_OK) return s;
  return TD_OK;
}

static inline td_status_t node_ipc_walked_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_walked_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 20, 4) != TD_OK) return TD_ERR_PROTOCOL;
  {
  uint32_t n0, b0;
  if (td_wire_load_vector(r, o + 0, 16, &n0, &b0) != 1) return TD_ERR_PROTOCOL;
  node_ipc_qid_t *e0 = (node_ipc_qid_t *)td_wire_alloc(a, n0 * (uint32_t)sizeof(node_ipc_qid_t), (uint32_t)_Alignof(node_ipc_qid_t));
  if (n0 && !e0) return TD_ERR_BUFFER_TOO_SMALL;
  for (uint32_t i0 = 0; i0 < n0; i0++) {
  if ((s = node_ipc_qid_decode(r, b0 + i0 * 16, a, &(e0[i0]))) != TD_OK) return s;
  }
  (out->qids).items = (const node_ipc_qid_t *)e0;
  (out->qids).count = n0;
  }
  if (td_wire_load_handle_opt(r, o + 16, &(out->node)) != TD_OK) return TD_ERR_PROTOCOL;
  return TD_OK;
}

static inline td_status_t node_ipc_change_encode(td_wire_msg_t *m, uint32_t o, const node_ipc_change_t *in) {
  td_status_t s = TD_OK;
  (void)s;
  td_wire_store(m, o + 0, (uint64_t)(in->seq), 8);
  td_wire_store(m, o + 8, (uint64_t)(in->kind), 1);
  if ((s = td_wire_store_bytes(m, o + 16, (in->name).data, (in->name).len)) != TD_OK) return s;
  return TD_OK;
}

static inline td_status_t node_ipc_change_decode(td_wire_reader_t *r, uint32_t o, td_wire_arena_t *a, node_ipc_change_t *out) {
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  (void)a;
  if (td_wire_check_padding(r, o + 9, 7) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, o + 0, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  out->seq = (uint64_t)(uint64_t)v;
  if (td_wire_load(r, o + 8, 1, &v) != TD_OK || !node_ipc_change_kind_known(v)) return TD_ERR_PROTOCOL;
  out->kind = (node_ipc_change_kind_t)(uint8_t)v;
  if (td_wire_load_string(r, o + 16, &(out->name).data, &(out->name).len) != TD_OK) return TD_ERR_PROTOCOL;
  return TD_OK;
}

// walk: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_walk_encode(td_wire_msg_t *m, uint32_t txid, node_ipc_vec_str_t names) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_WALK_ORDINAL, 16);
  if (s != TD_OK) return s;
  {
  uint32_t b0;
  if ((s = td_wire_store_vector(m, 0, (names).count, 16, &b0)) != TD_OK) return s;
  for (uint32_t i0 = 0; i0 < (names).count; i0++) {
  if ((s = td_wire_store_bytes(m, b0 + i0 * 16, ((names).items[i0]).data, ((names).items[i0]).len)) != TD_OK) return s;
  }
  }
  return TD_OK;
}

// walk: decodes the reply.
static inline td_status_t node_walk_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, node_ipc_walked_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 24) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = node_ipc_walked_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// walk: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_walk(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, node_ipc_vec_str_t names, td_wire_arena_t *arena, node_ipc_walked_t *result) {
  td_status_t s = node_walk_encode(buf, txid, names);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_walk_decode_reply(buf, arena, result);
}

// stat: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_stat_encode(td_wire_msg_t *m, uint32_t txid, uint32_t fields) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_STAT_ORDINAL, 8);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(fields), 4);
  return TD_OK;
}

// stat: decodes the reply.
static inline td_status_t node_stat_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, node_ipc_stat_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 64) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = node_ipc_stat_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// stat: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_stat(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint32_t fields, td_wire_arena_t *arena, node_ipc_stat_t *result) {
  td_status_t s = node_stat_encode(buf, txid, fields);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_stat_decode_reply(buf, arena, result);
}

// readdir: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_readdir_encode(td_wire_msg_t *m, uint32_t txid, uint64_t cursor, uint32_t max, uint32_t fields) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_READDIR_ORDINAL, 16);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(cursor), 8);
  td_wire_store(m, 8, (uint64_t)(max), 4);
  td_wire_store(m, 12, (uint64_t)(fields), 4);
  return TD_OK;
}

// readdir: decodes the reply.
static inline td_status_t node_readdir_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, node_ipc_dir_batch_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 32) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = node_ipc_dir_batch_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// readdir: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_readdir(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint64_t cursor, uint32_t max, uint32_t fields, td_wire_arena_t *arena, node_ipc_dir_batch_t *result) {
  td_status_t s = node_readdir_encode(buf, txid, cursor, max, fields);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_readdir_decode_reply(buf, arena, result);
}

// read: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_read_encode(td_wire_msg_t *m, uint32_t txid, uint64_t offset, uint32_t max) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_READ_ORDINAL, 16);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(offset), 8);
  td_wire_store(m, 8, (uint64_t)(max), 4);
  return TD_OK;
}

// read: decodes the reply.
static inline td_status_t node_read_decode_reply(const td_wire_msg_t *m, const uint8_t **result, uint32_t *result_len) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 16) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load_bytes(r, 0, result, result_len) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// read: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_read(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint64_t offset, uint32_t max, const uint8_t **result, uint32_t *result_len) {
  td_status_t s = node_read_encode(buf, txid, offset, max);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_read_decode_reply(buf, result, result_len);
}

// write: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_write_encode(td_wire_msg_t *m, uint32_t txid, uint64_t offset, const uint8_t *data, uint32_t data_len) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_WRITE_ORDINAL, 24);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(offset), 8);
  if ((s = td_wire_store_bytes(m, 8, (((td_wire_bytes_t){ data, data_len })).data, (((td_wire_bytes_t){ data, data_len })).len)) != TD_OK) return s;
  return TD_OK;
}

// write: decodes the reply.
static inline td_status_t node_write_decode_reply(const td_wire_msg_t *m, uint32_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 8) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_check_padding(r, 4, 4) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, 0, 4, &v) != TD_OK) return TD_ERR_PROTOCOL;
  (*result) = (uint32_t)(uint32_t)v;
  return td_wire_read_end(r);
}

// write: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_write(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint64_t offset, const uint8_t *data, uint32_t data_len, uint32_t *result) {
  td_status_t s = node_write_encode(buf, txid, offset, data, data_len);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_write_decode_reply(buf, result);
}

// watch: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_watch_encode(td_wire_msg_t *m, uint32_t txid, uint64_t seq) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_WATCH_ORDINAL, 8);
  if (s != TD_OK) return s;
  td_wire_store(m, 0, (uint64_t)(seq), 8);
  return TD_OK;
}

// watch: decodes the reply.
static inline td_status_t node_watch_decode_reply(const td_wire_msg_t *m, uint64_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 8) != TD_OK) return TD_ERR_PROTOCOL;
  if (td_wire_load(r, 0, 8, &v) != TD_OK) return TD_ERR_PROTOCOL;
  (*result) = (uint64_t)(uint64_t)v;
  return td_wire_read_end(r);
}

// watch: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_watch(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, uint64_t seq, uint64_t *result) {
  td_status_t s = node_watch_encode(buf, txid, seq);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_watch_decode_reply(buf, result);
}

// changed (event): decodes it.
static inline td_status_t node_changed_decode(const td_wire_msg_t *m, node_ipc_change_t *change) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 32) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = node_ipc_change_decode(r, 0, a, &((*change)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// create: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_create_encode(td_wire_msg_t *m, uint32_t txid, const char *name, uint32_t name_len, node_ipc_node_kind_t kind) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_CREATE_ORDINAL, 24);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ name, name_len })).data, (((td_wire_str_t){ name, name_len })).len)) != TD_OK) return s;
  td_wire_store(m, 16, (uint64_t)(kind), 1);
  return TD_OK;
}

// create: decodes the reply.
static inline td_status_t node_create_decode_reply(const td_wire_msg_t *m, td_wire_arena_t *a, node_ipc_walked_t *result) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  if (td_wire_read_begin(r, m, 24) != TD_OK) return TD_ERR_PROTOCOL;
  if ((s = node_ipc_walked_decode(r, 0, a, &((*result)))) != TD_OK) return s;
  return td_wire_read_end(r);
}

// create: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_create(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *name, uint32_t name_len, node_ipc_node_kind_t kind, td_wire_arena_t *arena, node_ipc_walked_t *result) {
  td_status_t s = node_create_encode(buf, txid, name, name_len, kind);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_create_decode_reply(buf, arena, result);
}

// remove: encodes the request. txid is the caller's, nonzero.
static inline td_status_t node_remove_encode(td_wire_msg_t *m, uint32_t txid) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, NODE_REMOVE_ORDINAL, 0);
  if (s != TD_OK) return s;
  return TD_OK;
}

// remove: decodes the reply.
static inline td_status_t node_remove_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// remove: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t node_remove(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code) {
  td_status_t s = node_remove_encode(buf, txid);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return node_remove_decode_reply(buf);
}

#ifdef __cplusplus
}
#endif

#endif
