// SPDX-License-Identifier: BSD-3-Clause
//
// Generated by idlc from lib/node/Srv.swift. Do not edit.
//
// Library todhchai.srv, version 1: the client side in C.
// Strings are pointer plus length (UTF-8, not NUL-terminated); optional
// values are pointers, NULL when absent (TD_HANDLE_INVALID for handles).
// What a reply returns points into the message buffer the call was
// given, and into the arena for vectors' elements and optional values.

#ifndef SRV_IPC_IDL_H
#define SRV_IPC_IDL_H

#include <stdbool.h>
#include <stdint.h>
#include <td_wire.h>

#ifdef __cplusplus
extern "C" {
#endif

#define BOARD_PROTOCOL_ID "todhchai.srv.Board"
#define BOARD_VERSION 1
#define BOARD_POST_ORDINAL UINT64_C(0x4cc8abd3ab346a3c)
#define BOARD_WITHDRAW_ORDINAL UINT64_C(0x75e0ca23bc8dd6a0)

// BoardError: codes in error replies (td_wire_call returns TD_ERR_REMOTE).
#define BOARD_ERROR_EXISTS 1
#define BOARD_ERROR_NOT_FOUND 2
#define BOARD_ERROR_BAD_NAME 3

// post: encodes the request. txid is the caller's, nonzero.
static inline td_status_t board_post_encode(td_wire_msg_t *m, uint32_t txid, const char *name, uint32_t name_len, td_handle_t node) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, BOARD_POST_ORDINAL, 24);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ name, name_len })).data, (((td_wire_str_t){ name, name_len })).len)) != TD_OK) return s;
  if ((s = td_wire_store_handle(m, 16, node)) != TD_OK) return s;
  return TD_OK;
}

// post: decodes the reply.
static inline td_status_t board_post_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// post: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t board_post(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *name, uint32_t name_len, td_handle_t node) {
  td_status_t s = board_post_encode(buf, txid, name, name_len, node);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return board_post_decode_reply(buf);
}

// withdraw: encodes the request. txid is the caller's, nonzero.
static inline td_status_t board_withdraw_encode(td_wire_msg_t *m, uint32_t txid, const char *name, uint32_t name_len) {
  td_status_t s = td_wire_begin(m, txid, TD_WIRE_REQUEST, 0, BOARD_WITHDRAW_ORDINAL, 16);
  if (s != TD_OK) return s;
  if ((s = td_wire_store_bytes(m, 0, (((td_wire_str_t){ name, name_len })).data, (((td_wire_str_t){ name, name_len })).len)) != TD_OK) return s;
  return TD_OK;
}

// withdraw: decodes the reply.
static inline td_status_t board_withdraw_decode_reply(const td_wire_msg_t *m) {
  td_wire_reader_t rd, *r = &rd;
  td_status_t s = TD_OK;
  uint64_t v;
  (void)s;
  (void)v;
  td_wire_arena_t *a = NULL;
  (void)a;
  if (td_wire_read_begin(r, m, 0) != TD_OK) return TD_ERR_PROTOCOL;
  return td_wire_read_end(r);
}

// withdraw: calls the method and waits for its reply. buf holds the
// request, then the reply. Returns TD_ERR_REMOTE with *error_code set if
// the method failed.
static inline td_status_t board_withdraw(td_handle_t channel, uint32_t txid, td_wire_msg_t *buf, int32_t *error_code, const char *name, uint32_t name_len) {
  td_status_t s = board_withdraw_encode(buf, txid, name, name_len);
  if (s != TD_OK) return s;
  if ((s = td_wire_call(channel, buf, txid, buf, error_code)) != TD_OK) return s;
  return board_withdraw_decode_reply(buf);
}

#ifdef __cplusplus
}
#endif

#endif
